<a href="https://colab.research.google.com/github/lacouth/metodos_20191/blob/master/Decomposicao_LU_aula_29_Abril_2019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/lacouth/metodos_20191/master)

In [0]:
# NO CANTO SUPERIOR CLICK EM "NOT TRUSTED" PARA HABILITAR OS JS DO NOTEBOOK

import jupytergraffiti #NÃO EXECUTAR ESSA CÉLULA NO GOOGLE COLAB

# <span class="graffiti-highlight graffiti-id_rh7iqpp-id_fydf14x"><i></i>A Decomposição LU</span>

## Teoria

Um sistema de equações lineares pode ser escrito como: 

$$ [A]_{n \times n} [X]_{n \times 1} = [B]_{n \times 1} $$

Podemos decompor $[A]$ como:

$$ [A] = [L][U] $$

onde $[L]$ é uma matriz triangular inferior e $[U]$ é uma matriz triangular superior.

Teremos então:

$$ [L][U][X] = [B] $$

multiplicando os dois lados por $[L]^{-1}$ obtemos:

$$ [L]^{-1} [L][U][X] = [L]^{-1}[B] $$

Sabemos que qualquer matriz multiplicada pela sua inversa é igual a matriz identidade, logo:

$$ [I][U][X] = [L]^{-1}[B] $$

sabemos também que qualquer matriz multiplicada pela matriz identidade é a própria matriz, então:

$$ [U][X] = [L]^{-1}[B] $$

fazendo $[Z] = [L]^{-1}[B] $, temos:

$$ [U][X] = [Z] $$

Sabemos que $ [L]^{-1}[B] = [Z] $, multiplicamos os dos lados da equação por $[L]$ para obter:

$$ [L][L]^{-1}[B] = [L] [Z] $$
$$ [I][B] = [L][Z] $$
$$ [B] = [L][Z] $$

Ficamos com dois sistemas:

$$ [L][Z] = [B] $$
$$ [U][X] = [Z] $$

Expandindo: 

$$\begin{bmatrix}\times & 0 & 0\\
\times &\times  & 0\\
\times &\times  &\times
\end{bmatrix}
\begin{bmatrix}
z_1\\
z_2\\
z_3
\end{bmatrix}
=
\begin{bmatrix}
b_1\\
b_2\\
b_3
\end{bmatrix}$$

$$\begin{bmatrix}
\times & \times & \times \\ 
0 &\times  & \times\\ 
0 &0  &\times 
\end{bmatrix}
\begin{bmatrix}
x_1\\
x_2\\
x_3
\end{bmatrix}
=
\begin{bmatrix}
z_1\\
z_2\\
z_3
\end{bmatrix}$$

## <span class="graffiti-highlight graffiti-id_mntiqbu-id_0pn8c4m"><i></i>A Decomposição LU : Decompondo a matriz [A]</span>

$$ [A] = \begin{bmatrix}25 & 5 & 1\\
64 & 8  & 1\\
144 & 12  & 1
\end{bmatrix}$$

$$ [A] = [L][U] $$

In [0]:
import numpy as np
np.set_printoptions(formatter={'float': lambda x: "{:.3f}".format(x)})

In [0]:
A = np.array([[25,5,1],[64,8,1],[144,12,1]],dtype = float)
A

array([[25.000, 5.000, 1.000],
       [64.000, 8.000, 1.000],
       [144.000, 12.000, 1.000]])

In [0]:
def decompor_matriz(M):
  U = M.copy()
  L = np.identity(M.shape[0])
  passos = M.shape[0]-1
  for p in range(passos):
    pivo = U[p,p]
    for i in range(p+1,M.shape[0]):
      m = U[i,p]/pivo
      L[i,p] = m
      U[i] = U[i] - U[p]*m
  
  return L,U

In [0]:
L,U = decompor_matriz(A)
L

array([[1.000, 0.000, 0.000],
       [2.560, 1.000, 0.000],
       [5.760, 3.500, 1.000]])

In [0]:
U

array([[25.000, 5.000, 1.000],
       [0.000, -4.800, -1.560],
       [0.000, 0.000, 0.700]])

In [0]:
np.dot(L,U)

array([[25.000, 5.000, 1.000],
       [64.000, 8.000, 1.000],
       [144.000, 12.000, 1.000]])

# <span class="graffiti-highlight graffiti-id_12xb54z-id_uoiiol1"><i></i>Encontrando a matriz inversa : Teoria</span>

Vamos supor que alguém pede para você encontrar a inversa de uma matriz quadrada $[A]_{n\times n}$. O que você basicamente tem que encontrar é uma matriz de mesma ordem que multiplicada pela matriz $[A]$ resulte em uma matriz identidade:

$$[A]_{n\times n} [X]_{n\times n} = [I]_{n\times n} $$

$$\begin{bmatrix}
a_{11} & a_{12} & a_{13} & \ldots & a_{1n} \\
a_{21} & a_{22} & a_{23} & \ldots & a_{2n} \\
\vdots & &\ddots & & \vdots \\
a_{n1} & a_{n2} & a_{n3} & \ldots & a_{nn} \\
\end{bmatrix}
\begin{bmatrix}
x_{11} & x_{12} & x_{13} & \ldots & x_{1n} \\
x_{21} & x_{22} & x_{23} & \ldots & x_{2n} \\
\vdots & &\ddots & &\vdots \\
x_{n1} & x_{n2} & x_{n3} & \ldots & x_{nn} \\
\end{bmatrix}
=
\begin{bmatrix}
1 & 0 & 0 & \ldots & 0 \\
0 & 1 & 0 & \ldots & 0 \\
\vdots & &\ddots & &\vdots \\
0 & 0 & 0 & \ldots & 1 \\
\end{bmatrix}
$$

Essa relação resulta em uma série de sistemas lineares. Por exemplo, para encontrar a primeira coluna da matriz $[X]$ você pode resolver o seguinte sistema:

$$\begin{bmatrix}
a_{11} & a_{12} & a_{13} & \ldots & a_{1n} \\
a_{21} & a_{22} & a_{23} & \ldots & a_{2n} \\
\vdots & &\ddots & & \vdots \\
a_{n1} & a_{n2} & a_{n3} & \ldots & a_{nn} \\
\end{bmatrix}
\begin{bmatrix}
x_{11}\\
x_{21}\\
x_{31}\\
\vdots\\
x_{n1}
\end{bmatrix}
=
\begin{bmatrix}
1\\
0\\
0\\
\vdots\\
0
\end{bmatrix}$$

Para encontrar a segunda coluna da matriz $[X]$ então resolvemos o sistema agora para a segunda coluna da matriz identidade:

$$\begin{bmatrix}
a_{11} & a_{12} & a_{13} & \ldots & a_{1n} \\
a_{21} & a_{22} & a_{23} & \ldots & a_{2n} \\
\vdots & &\ddots & & \vdots \\
a_{n1} & a_{n2} & a_{n3} & \ldots & a_{nn} \\
\end{bmatrix}
\begin{bmatrix}
x_{12}\\
x_{22}\\
x_{32}\\
\vdots\\
x_{n2}
\end{bmatrix}
=
\begin{bmatrix}
0\\
1\\
0\\
\vdots\\
0
\end{bmatrix}$$

Montamos sucessivos sistemas até a coluna $n$:

$$\begin{bmatrix}
a_{11} & a_{12} & a_{13} & \ldots & a_{1n} \\
a_{21} & a_{22} & a_{23} & \ldots & a_{2n} \\
\vdots & &\ddots & & \vdots \\
a_{n1} & a_{n2} & a_{n3} & \ldots & a_{nn} \\
\end{bmatrix}
\begin{bmatrix}
x_{1n}\\
x_{2n}\\
x_{3n}\\
\vdots\\
x_{nn}
\end{bmatrix}
=
\begin{bmatrix}
0\\
0\\
0\\
\vdots\\
n
\end{bmatrix}$$

## <span class="graffiti-highlight graffiti-id_nkrtf84-id_43iyt1v"><i></i>Utilizando a decomposição LU</span>

Para evitar ter que aplicar o passo da eliminação de Gauss em todos os sistemas, podemos decompor $[A]$ em duas matrizes $[L][U]$ e para cada sistema resolver apenas os passos de substituição.

Então para encontrar a primeira coluna da matriz inversa, fazemos primeiro:

$$\begin{bmatrix}
\times & 0 & 0\\
\times &\times & 0\\
\times &\times & \times
\end{bmatrix}
\begin{bmatrix}
z_{1}\\
z_{2}\\
z_{3}\\
\end{bmatrix}
=
\begin{bmatrix}
1\\
0\\
0
\end{bmatrix}$$

e depois com os valores de $[Z]$ resolvemos:

$$\begin{bmatrix}
\times & \times & \times \\ 
0 &\times  & \times\\ 
0 &0  &\times 
\end{bmatrix}
\begin{bmatrix}
x_{11}\\
x_{21}\\
x_{31}
\end{bmatrix}
=
\begin{bmatrix}
z_{1}\\
z_{2}\\
z_{3}\\
\end{bmatrix}$$

Agora para encontrar a segunda coluna apenas trocamos a matriz de termos independentes do primeiro sistema:

$$\begin{bmatrix}
\times & 0 & 0\\
\times &\times & 0\\
\times &\times & \times
\end{bmatrix}
\begin{bmatrix}
z_{1}\\
z_{2}\\
z_{3}\\
\end{bmatrix}
=
\begin{bmatrix}
0\\
1\\
0
\end{bmatrix}$$

e depois com os valores de $[Z]$ resolvemos:

$$\begin{bmatrix}
\times & \times & \times \\ 
0 &\times  & \times\\ 
0 &0  &\times 
\end{bmatrix}
\begin{bmatrix}
x_{12}\\
x_{22}\\
x_{32}
\end{bmatrix}
=
\begin{bmatrix}
z_{1}\\
z_{2}\\
z_{3}\\
\end{bmatrix}$$

Resolvemos da mesma maneira até a coluna $n$ de $[X]$ mas apenas realizando as substituições diretas e reversas dos sistemas sem a necessidade dos passos de eliminação:

$$[L]
\begin{bmatrix}
z_{1}\\
z_{2}\\
z_{3}\\
\vdots\\
z_{n1}
\end{bmatrix}
=
\begin{bmatrix}
0\\
0\\
0\\
\vdots\\
1
\end{bmatrix}$$

e depois com os valores de $[Z]$ resolvemos:

$$[U]
\begin{bmatrix}
x_{1n}\\
x_{2n}\\
x_{3n}\\
\vdots\\
x_{nn}
\end{bmatrix}
=
\begin{bmatrix}
z_{1}\\
z_{2}\\
z_{3}\\
\vdots\\
z_{n1}
\end{bmatrix}$$

Dessa forma evitamos o passo mais complicado que é a eliminação de Gauss.

# <span class="graffiti-highlight graffiti-id_uoot1cg-id_37o8gx8"><i></i>Decomposição LU: Exemplo</span>

Encontrar a matriz inversa de:
$$ [A] = \begin{bmatrix}25 & 5 & 1\\
64 & 8  & 1\\
144 & 12  & 1
\end{bmatrix}$$

sabendo que:

$$[A][A]^{-1} = [I]$$


In [0]:
from scipy.linalg import solve_triangular
import numpy as np
np.set_printoptions(formatter={'float': lambda x: "{:.3f}".format(x)})

In [0]:
A = np.array([[25,5,1],[64,8,1],[144,12,1]],dtype = float)
A

array([[25.000, 5.000, 1.000],
       [64.000, 8.000, 1.000],
       [144.000, 12.000, 1.000]])

In [0]:
I = np.identity(A.shape[0])
Z = np.zeros(A.shape[0])
A_inv = np.zeros(A.shape)


In [0]:
L,U = decompor_matriz(A)

Z = solve_triangular(L,I[:,0], lower=True)
A_inv[:,0] = solve_triangular(U,Z)
A_inv

array([[0.048, 0.000, 0.000],
       [-0.952, 0.000, 0.000],
       [4.571, 0.000, 0.000]])

In [0]:
Z = solve_triangular(L, I[:,1], lower=True)
A_inv[:,1] = solve_triangular(U,Z)

Z = solve_triangular(L, I[:,2], lower=True)
A_inv[:,2] = solve_triangular(U,Z)
A_inv

array([[0.048, -0.083, 0.036],
       [-0.952, 1.417, -0.464],
       [4.571, -5.000, 1.429]])

In [0]:
np.dot(A,A_inv)

array([[1.000, 0.000, 0.000],
       [0.000, 1.000, 0.000],
       [0.000, -0.000, 1.000]])

# Exercícios

1. Calcule a decomposição LU de cada uma das matrizes abaixo:

    a. 
$$ A = \begin{bmatrix}2 & 1 \\-4 & -6\end{bmatrix}$$
    b.
$$ A = \begin{bmatrix}2 & 1 & -4 \\2 & 2 & -2\\6&3&-11\end{bmatrix}$$
    c.
$$ A = \begin{bmatrix}1 & 3 & 2 \\2 & 8 & 5\\1&11&4\end{bmatrix}$$

2. Encontre as matrizes inversas de cada um dos itens anteriores