# EDO

## Equações diferenciais ordinárias

As equações diferenciais são aquelas equações que relacionam uma função a uma ou mais de suas derivadas. Isso significa que a solução delas é uma função. Por exemplo:

$$y'' + 2y' = 3y$$

onde uma das soluções possíveis é: $y = e^{-3x}$,pois 

$$9e^{-3x}-6e^{-3x} = 3e^{-3x}$$

outras funções, ou mesmo uma classe de funções, podem satisfazer uma EDO.

## O Método de Euler

Numericamente o objetivo passa a ser reconstruir ponto a ponto a função de interesse. Para isso precisamos que ao menos um ponto inicial seja conhecido, por isso esse tipo de problema também é conhecido como **Problema de Valor Inicial** (PVI).

O método de Euler é conceitualmente simples, sua base é a série de Taylor truncada :

$$f(x+h) = f(x) + hf'(x)$$

Como o método prediz a função em $x+h$ a partir da informação disponível em $x$, ela pode ser usada para mover a solução em passos de largura $h$. A figura abaixo ilustra esse conceito.

![](exemplo_euler.png)

### Exemplo:

1. Dada a seguinte equação diferencial:

$$\frac{dy}{dx} + 0.4y(x) = 3e^{-x}$$

sabendo que y(0) = 5, encontre y(3).

**solução**

Considerando por simplicidade:

$$\frac{dy}{dx} = f(x,y(x)) = f(x,y)$$

temos

$$f(x,y) + 0.4y(x) = 3e^{-x}$$

O primeiro passo é reescrever a equação isolando $f(x,y)$.

$$f(x,y) = 3e^{-x} - 0.4y(x)$$

Utilizando $h=3$ partindo de $x=0$, através do método de Euler temos que:

$y(x+h) = y(x)+hf(x,y)$

$y(0+3) = f(0) +3(f(0,5))$

$y(3) = 5 + 3(3e^{-0} - 0.4y(0))$

$y(3) = 5 + 3(3 - 0.4(5))$

$y(3) = 8 $

A solução exata é $y(3) = 2.7563$, o que resulta em um erro real $|\epsilon_r| = 190\%$.

**solução 2**

Para melhorar o resultado podemos diminuir o intervalo $h$.

Utilizando $h=1.5$ teremos que fazer duas iterações do método para chegar no ponto $x=3$

$$0 \implies 1.5 \implies 3$$

**1ª iteração**

$0 \implies 1.5$

$y(0+1.5) = y(0) + 1.5(f(0,y(0))$

$y(1.5) = 5 + 1.5(3e^{-0} - 0.4y(0))$

$y(1.5) = 6.5$

**2ª iteração**

$1.5 \implies 3$

$y(1.5+1.5) = y(1.5) + 1.5(f(1.5,y(1.5))$

$y(3) = 6.5 + 1.5(3e^{-0} - 0.4y(1.5))$

$y(3) = 3.604$

A solução exata é $y(3) = 2.7563$, o que resulta em um erro real $|\epsilon_r| = 30.44\%$.

**solução 3 (Implementando em python)**


In [1]:
import numpy as np

## definindo a dx/dy =f(x,y) do problema
def fxy(x,y):
    return 3*np.exp(-x)-0.4*y 

In [29]:
#implementando o método de Euler
# a função recebe: 
# dx/dy = f(x,y), 
# o valor inicial y0,
# o valor inicial de x0,
# o valor final de xf a ser calculado
# o passo entre cada iteração h

def euler(fxy, y0, x0,xf, h):
    it = int((xf - x0)/h) # calcula quantas iterações são necessárias para chegar a xf
    y = np.zeros(it+1)
    y[0] = y0
    for i in range(it):
        y[i+1] = y[i]+h*fxy(x0+i*h,y[i])
    return y
        

In [35]:
euler(fxy,y0=5,x0=0,xf=3,h=3) # 1 iteração

array([5., 8.])

In [36]:
euler(fxy,y0=5,x0=0,xf=3,h=1.5) # 2 iterações

array([5.        , 6.5       , 3.60408572])

In [45]:
y_3 = euler(fxy,y0=5,x0=0,xf=3,h=0.3) # 10 iterações
y_3

array([5.        , 5.3       , 5.3307364 , 5.1849785 , 4.92869378,
       4.60832531, 4.25614342, 3.89417521, 3.53708497, 3.19428093,
       2.87145218])

In [46]:
# calculando o erro real para 10 iterações

erro = np.abs((2.7563 - y_3[-1])/2.7563)*100
erro

4.177781122947298

# Os métodos de Runge-Kutta

O método de Euler é classificado como um método de primeira ordem porque sua base foi a série de Taylor truncada. A precisão numérica pode ser melhorada, mantendo mais termos da série. Assim, um método de enésima ordem usaria a série truncada de Taylor até o enésimo termo.

$$f(x+h) = f(x) + hf'(x) + \frac{h^2}{2!}f''(x) + \dots + \frac{h^n}{n!}f^n(x)$$

Mas agora teriamos que derivar expressões para $f''(x)$, $f'''(x)$, ... $f^{n}(x)$ e escrever subrotinas para calcular elas. Esse trabalho extra pode ser evitado pelo uso dos métodos de Runge-Kutta que são baseados na série de Taylo truncada mas não requerem o cálculo de derivas de alta ordem.

## Runge-Kutta de 2ª Ordem

Para chegar ao método Runge-Kutta de segunda ordem, assumimos que a fórmula:

$y_{i+1} = y_i + (a_1k_1 + a_2k_2)h$

onde

$k_1 = f(x_i,y_i)$

$k_2 = f(x_i+p_1h, y_i+q_{11}k_1h)$

é igual a série de Taylor de segunda ordem:

$y_{i+1} = y_i + (a_1k_1 + a_2k_2)h = y_i + hf(x_i,y_i) + \frac{h^2}{2!}f'(x_i,y_i)$

Fazendo isso, um sistema de três equações pode ser derivado para encontrar as quatro constantes desconhecidas. As três equações são:

$a_1 + a_2 = 1$

$a_2p_1 = 1/2$

$a_2q_{11} = 1/2$

Como temos três equações com quatro incógnitas, essas equações são consideradas indeterminadas. Nós, portanto, devemos assumir (**chutar**) um valor de uma das constantes para determinar os outros três. Suponha que especificamos um valor para $a_2$. Então as equações podem ser resolvidas como:

$a_1 = 1 - a_2$

$p_1=q_{11}=\frac{1}{2a_2}$

Como podemos escolher um número infinito de valores para $a_2$, há um número infinito de métodos RK de segunda ordem. Três das versões mais usadas e preferidas são apresentadas a seguir:

## Método de Heun ( $a_2 = \frac{1}{2} $ )

Se $a_2 = \frac{1}{2}$ obtemos

$a_1 = 1 - a_2$

$a_1 = \frac{1}{2}$

e

$p_1=q_{11}=\frac{1}{2a_2}$

$p_1=q_{11}=1$

logo a equação de atualização de Runge-Kutta passa a ser:

$y_{i+1} = y_i + \left(\frac{1}{2}k_1 + \frac{1}{2}k_2\right)h$

onde

$k_1 = f(x_i,y_i)$

$k_2 = f(x_i+h, y_i + k_1h)$


## Método do ponto médio ($a_2 = 1$)

Temos como chute $a_2 = 1$, logo

$a_1 = 0$

$p_1 = q_{11} = \frac{1}{2}$

logo

$y_{i+1} = y_i + k_2h$

onde

$k_1 = f(x_i,y_i)$

$k_2 = f(x_i+\frac{1}{2}h, y_i + \frac{1}{2}k_1h)$

## Método de Ralston  ($ a_2 = \frac{2}{3} $)

$a_1 = \frac{1}{3}$

$p_1 = q_{11} = \frac{3}{4}$

logo a equação de atualização de Runge-Kutta passa a ser:

$y_{i+1} = y_i + \left(\frac{1}{3}k_1 + \frac{2}{3}k_2\right)h$

onde

$k_1 = f(x_i,y_i)$

$k_2 = f(x_i+\frac{3}{4}h, y_i + \frac{3}{4}k_1h)$

## Exemplo 

1. Dada a seguinte equação diferencial:

$$\frac{dy}{dx} + 0.4y(x) = 3e^{-x}$$

sabendo que y(0) = 5, encontre y(3), utilizando $h = 1.5$.

**solução**

Primeiro obtemos $f(x,y)$:

$f(x,y) = 3e^{-x}-0.4y$

Depois utilizando o método de Heun

Para a primeira iteração $i=0$, temos $y(0) = y_0 = 5$ e 

$k_1 = f(x_0, y_0) = 3e^{-0} - 0.4(5) = 1$

$k_2 = f(x_0+h, y_0 + k_1h) = f(1.5,6.5) = 3e{-1.5} - 0.4(6.5) = -1.9306$

logo

$y_1 = y_0 + \left(\frac{1}{2}k_1+\frac{1}{2}k_2\right)h$

$y_1 = 5 + \left(\frac{1}{2}(1)+\frac{1}{2}(-1.9306)\right)(1.5) = 4.302$

$y_1 = y(1.5) = 4.302$

Na segunda iteração $i=1$, temos $x_1 = 1.5$ e $y_1 = 4.302$

$k_1 = f(x_1, y_1) = 3e^{-1.5} - 0.4(4.302) = -1.0519$

$k_2 = f(x_0+h, y_0 + k_1h) = f(3,2.7206) = 3e{-3} - 0.4(2.7206) = -0.9406$

logo

$y_2 = y_1 + \left(\frac{1}{2}k_1+\frac{1}{2}k_2\right)h$

$y_2 = 4.302 + \left(\frac{1}{2}(-1.0519)+\frac{1}{2}(-0.9406)\right)(1.5) = 2.808$

$y_2 = y(3) = 2.808$

O erro real $|\epsilon_r| = 1.63\%$

**solução 2 (Implementando em python)**


In [47]:
import numpy as np

def fxy(x,y):
    return 3*np.exp(-x)-0.4*y

In [52]:
def metodo_heun(fxy, x0, y0, xf, h):
    it = int((xf-x0)/h)
    y = np.zeros(it+1)
    y[0] = y0
    for i in range(it):
        xi = x0+i*h
        k1 = fxy(xi,y[i])
        k2 = fxy(xi+h,y[i]+h*k1)
        y[i+1] = y[i] + (k1+k2)*h/2
    return y

In [53]:
y_3 = metodo_heun(fxy,0,5,3,1.5) # Método de Heun com 2 iterações
y_3

array([5.        , 4.30204286, 2.80802291])

In [54]:
y_3 = metodo_heun(fxy,0,5,3,1) # Método de Heun com 3 iterações
y_3

array([5.        , 4.85181916, 3.83333145, 2.80314774])

In [55]:
y_3 = metodo_heun(fxy,0,5,3,0.3) # Método de Heun com 10 iterações
y_3

array([5.        , 5.1653682 , 5.12304392, 4.94545032, 4.6841425 ,
       4.37545271, 4.04464569, 3.70897341, 3.37991703, 3.06482918,
       2.76813401])

In [56]:
# calculando o erro real para 10 iterações
erro_real = np.abs((2.763 - y_3[-1])/2.763)*100
erro_real

0.18581294544428179

# Exercício

Resolva o problema anterior utilizando as equações de atualização dos métodos do ponto médio e do método de Ralston. **Dica: nenhum deles obtém melhor resultado do que o de Heun com os mesmos parâmetros**

# Método Runge-Kutta de Quarta Ordem

Os métodos RK mais populares são os de quarta ordem. Assim como nas abordagens de segunda ordem, há um número infinito de versões. O seguinte é a forma mais comumente usada e, portanto, a chamamos de método RK de quarta ordem clássico:

$$y_{i+1} = y_i + \frac{1}{6}(k_1 + 2k_2 + 2k_3 + k_4)h$$

onde, 

$k_1 = f(x_i,y_i)$

$k_2 = f(x_i + \frac{h}{2}, y_i+\frac{h}{2}k_1)$

$k_3 = f(x_i + \frac{h}{2}, y_i+\frac{h}{2}k_2)$

$k_4 = f(x_i + h, y_i+hk_3)$

## Exercício

1. Dada a seguinte equação diferencial:

$$\frac{dy}{dx} + 0.4y(x) = 3e^{-x}$$

sabendo que y(0) = 5, encontre y(3), com $h = 1.5$. Utilize o método RK4 clássico.

**Resposta**

$y(3) \approx 2.7588$