In [ ]:
import numpy as np
#import matplotlib.pyplot as plt
#from scipy.linalg import lu, solve_triangular, solve

np.set_printoptions(formatter={'float': lambda x: "{:.3f}".format(x)})

# Projeto de Sistemas Lineares

[Fonte - Problema 4](http://www.mtm.ufsc.br/~daniel/7105/Maria_Regina_Nunes_Lamin.PDF)

Parabéns, o **Instituto Federal de Ciência e Tecnologia do Estado da Paraíba - IFPB** nomeou você para ser o tesoureiro das barracas de salgados durante a Gincana Estudantil que ocorrerá em **12/10/2019**. 

Estará sob sua responsabilidade 3 barracas de salgados que terão o mesmo cardápio, com os seguintes itens: *Cachorro-quente*, *Pastéis* e *Porções de batatas fritas*. O preço de cada item será o mesmo em qualquer uma das barracas de salgados.

Após o evento, você terá de fazer um balanço sobre o consumo dos itens, e prestar contas dos rendimentos dos salgados.

## O Problema

Você não foi informado do preço de cada item disponível no cardápio. Os dados que te passaram foram as quantidades dos itens que foram vendidos em cada barraca, e o montante arrecadado em cada barraca.

Precisamos saber o valor de cada item para passar a informação correta e completa para a organização do evento e para os responsáveis pela instituição de ensino **IFPB**.

#### Dados:

* Barraca de João Henrique foram vendidos 28 cachorros-quentes, 42 pastéis e 48 porções de batatas-fritas, com uma arrecadação total de 102,00 R$.

* Barraca de Lucimara Alves foram consumidos 23 cachorros-quentes, 50 pastéis e 45 porções de batatas-fritas, com arrecadação total de 95,00 R$.

* Barraca de Bianca Pachêco foram consumidos 30 cachorros-quentes, 45 pastéis e 60 porções de batatas-fritas, com arrecadação total de 117,00 R$.

Para facilitar nossa análise faremos a substituição dos itens por siglas, tal que:

* **$x_1$** - representará a quantidade de cachorros-quentes consumidos;
* **$x_2$** - representará a quantidade de pastéis consumidos;
* **$x_3$** - representará a quantidade de porções de batatas-fritas consumidas.

Com isso, para resolvermos o nosso cálculo montaremos nosso sistema de equações lineares da seguinte forma:

Barraca de João Henrique:  $ 28x_1 + 42x_2 + 48x_3 = 102,00 R$  $

Barraca de Lucimara Alves: $ 23x_1 + 50x_2 + 45x_3 = 95,00 R$  $

Barraca da Bianca: $ 30x_1 + 45x_2 + 60x_3 = 117,00 R$  $

#### Sistema:


$$ 28x_1 + 42x_2 + 48x_3 = 102,00 R$  $$
$$ 23x_1 + 50x_2 + 45x_3 = 95,00 R$  $$
$$ 30x_1 + 45x_2 + 60x_3 = 117,00 R$  $$



## Resolvendo o sistema utilizando Gauss Ingênuo


#### Função: sistemalinear_gaussingenuo_etapa_eliminação ( matriz )

Esta função fará a etapa de eliminação, transformando a matriz em uma matriz diagonal superior.


In [ ]:
def sistemalinear_gaussingenuo_etapa_eliminacao(matriz):
  row = 0
  col = 0
  rowPivo = 0
  colPivo = 0
  posPivo = 0
  
  # Laço para a posição do pivô  
  for posPivo in range (0, np.shape(matriz)[0] - 1 ):  
    # Coleta o pivô
    pivo = matriz[posPivo, posPivo]  
    
    # Percorre as linhas da matriz abaixo do pivo para calcular o multiplixador
    for row in range (1+posPivo, np.shape(matriz)[0] ):
      # Calcula o multiplicador M
      multiply = matriz[row, posPivo] / pivo
      
      # Percorre as colunas da linha após a posição do pivô
      for col in range (posPivo, np.shape(matriz)[1]):
        # Calcula o valor da nova linha
        matriz[row, col] = (matriz[row, col] - (matriz[posPivo, col] * multiply)) 
  # Retorna a matriz após a etapa de eliminação      
  return matriz

def imprimeResultados(matriz):
  print("Preço dos itens:")
  print("Cachorro-quente = {}".format(np.around(matriz[0], decimals=3)))
  print("Pastel = {}".format(np.around(matriz[1], decimals=3)))
  print("Batatas-fritas = {}".format(np.around(matriz[2], decimals=3)))

#### Função: sistemalinear_etapa_substituicao ( matriz )

Essa função fará a substituição dos valores de X, resolvendo o sistema linear.

**Observação**: Este método pode ser (e será) aplicado, isto é, re-utilizado, a outras metodologias, como por exemplo: Pivotação Parcial.

In [ ]:
def sistemalinear_etapa_substituicao(matriz):
  x = []
  sum = []
  row = 0
  col = 0
  
  # Popula o array X de acordo com o tamanho da matriz do sistema 
  for idx in range(0, np.shape(matriz)[0]):
    x.append(0)
    sum.append(0)
  
  # Percorre as linhas de forma decrescente
  for row in range (np.shape(matriz)[0]-1, -1, -1):
    # Faz o somatorio
    sum[row] = 0
    for col in range (np.shape(matriz)[0]):
      #print("[{}, {}] Somatorio: {} += {} * {} ".format(row, col, sum[row], matriz[row, col], x[col]))
      sum[row] += matriz[row, col] * x[col]
      
      
    # Calcula o X
    #print("")
    #print("[{}, {}] {} = ( ( {} - {} ) / {})".format(row, col, x[row], matriz[row,(np.shape(matriz)[1] - 1)], sum[row], matriz[row,row]))
    x[row] = (matriz[row,(np.shape(matriz)[1] - 1)] - sum[row]) / matriz[row,row]
  
  return x;

#### Função: sistemalinear_calcula_por_gaussingenuo ()

Esta função realiza as duas etapas, eliminação e substituição, utilizando o método Gauss Ingênuo, retornando os valores de $x_{1}, x_{2},...,x_{n}$

In [ ]:
def sistemalinear_calcula_por_gaussingenuo(matriz):
  novamatriz = sistemalinear_gaussingenuo_etapa_eliminacao(matriz)
  resultado = sistemalinear_etapa_substituicao(novamatriz)
  return resultado;

### Resolução:

In [ ]:
gaussing_matriz = np.array([[28,42,48,102],[23,50,45,95],[30,45,60,117]], dtype=float)
gaussing_resultado = sistemalinear_calcula_por_gaussingenuo(gaussing_matriz)

print("Preço dos itens:")
print("Cachorro-quente = {}".format(np.around(gaussing_resultado[0], decimals=4)))
print("Pastel = {}".format(np.around(gaussing_resultado[1], decimals=4)))
print("Batatas-fritas = {}".format(np.around(gaussing_resultado[2], decimals=4)))

Preço dos itens:
Cachorro-quente = 1.5
Pastel = 0.4
Batatas-fritas = 0.9


## Resolvendo o sistema utilizando Gauss com pivotação parcial

#### Função: sistemalinear_pivotacaoparcial_etapa_eliminacao ( matriz )

Essa função realiza a etapa de substituição utilizando o método da pivotação parcial.


In [ ]:
def sistemalinear_pivotacaoparcial_etapa_eliminacao(matriz):
  row = 0
  col = 0
  posPivo = 0
  
  # Reposiciona as equações para eliminar divisão por zero
  for iPivo in range ( np.shape(matriz)[0] - 1 ):
    # Encontra o maior número absoluto na linha para definir o pivo
    if (np.argmax( np.abs( matriz[iPivo:,iPivo] ) ) != 0):
      # Reposiciona
      idxMax = iPivo + np.argmax( np.abs( matriz[iPivo:,iPivo] ) )
      matriz[[iPivo,idxMax]] = matriz[[idxMax,iPivo]] 
      
    pivo = matriz[iPivo, iPivo]  
    
    # Percorre as linhas
    for row in range (iPivo + 1, np.shape(matriz)[0] ):
      multiply = matriz[row, iPivo] / pivo
      # Percorre as colunas da linha
      for col in range (np.shape(matriz)[1]):
        # Processa a linha
        matriz[row, col] = matriz[row, col] - (matriz[iPivo, col] * multiply)    
  
  return matriz

#### Função: sistemalinear_calcula_por_pivotacaoparcial ()

Esta função realiza as duas etapas, eliminação e substituição, utilizando o método da Pivotação Parcial, retornando os valores de $x_{1}, x_{2},...,x_{n}$

In [ ]:
def sistemalinear_calcula_por_pivotacaoparcial(matriz):
  novamatriz = sistemalinear_pivotacaoparcial_etapa_eliminacao(matriz)
  resultado = sistemalinear_etapa_substituicao(novamatriz)
  return resultado

### Resolução:

In [ ]:
pivotacao_matriz = np.array([[28,42,48,102],[23,50,45,95],[30,45,60,117]], dtype=float)
pivotacao_resultado = sistemalinear_calcula_por_pivotacaoparcial(pivotacao_matriz)
imprimeResultados(pivotacao_resultado)


Preço dos itens:
Cachorro-quente = 1.5
Pastel = 0.4
Batatas-fritas = 0.9


## Resolvendo o sistema utilizando Gauss-Seidel


#### Função: sistemaslineares_verificaconvergencia_gaussseidel( matriz ) 

Essa função verifica se há convergência no sistema representado pela matriz passa como parâmetro.

##### Retorno: 

* **1**: se há convergância 
* **0**: se não há.



In [ ]:
def sistemaslineares_verificaconvergencia_gaussseidel(matriz):
  qty_itens_verdadeiro = 0
  for row in range (0, np.shape(matriz)[0]):
    somatorio_colunas = 0
    diagonal = 0
    
    for col in range (0, np.shape(matriz)[1]):
      if (row != col):
        somatorio_colunas += np.abs(matriz[row, col])
      else:
        diagonal = matriz[row, col]
    if (diagonal > somatorio_colunas):
      qty_itens_verdadeiro += 1
    
  if (qty_itens_verdadeiro == np.shape(matriz)[0]):
    return 1
  
  return 0

#### Função: sistemaslineares_calcula_por_gaussseidel( matriz ) 

Essa função calcula um sistema linear utilizando o método iterativo Gauss-Seidel.

##### Parâmetros:

1. **matriz_coeficiente** - Matriz contendo os coeficientes do sistema linear
2. **matriz_resultado** - Matriz contendo o resultado de cada sistema linear
3. **xInicial** - Matriz com o chute inicial
4. **ea** - Erro de Aproximação
5. **maxiterations** - Número máximo de iterações

##### Retornos:

1. **x** - Array com os valores de X
2. **erros** - Array com os erros de aproximação
3. **iteracoes** - Número de iterações para tentar resolver o sistema

In [ ]:
def sistemaslineares_calcula_por_gaussseidel(matriz_coeficientes, matriz_resultados, xInicial, ea=0.0001, maxiterations=100):
  x = []
  xPrevior = []
  erro_ap = []
  erros = []
  positionMaxError = 0.0

  # Popula o valor de X com valores iniciais 
  for idx in range(0, np.shape(matriz_coeficientes)[0]):
    x.append(0)
    xPrevior.append(0)
    erro_ap.append(0)  
  
  # Atribui o primeiro chute
  x[0] = xInicial
  
  for n in range (0, maxiterations):
    for row in range (0, np.shape(matriz_coeficientes)[0]):
      somatorio = 0;
      xPrevior[row] = x[row]
      for col in range (0, np.shape(matriz_coeficientes)[1]):
        if (col != row):
          somatorio += (matriz_coeficientes[row, col] * x[col])
          
      x[row] =  ( matriz_resultados[row] - ( somatorio ) ) / matriz_coeficientes[row, row]
      erro_ap[row] = np.abs((x[row] - xPrevior[row])/x[row])*100
      
      positionMaxError = np.argmax( np.abs( erro_ap[0:] ) )
      erros.append(erro_ap[positionMaxError])
      if ( (erro_ap[positionMaxError] <= ea) | (n >= maxiterations) ):
        return x, erros, n
        
  return x, erros, n

### Resolução:


In [ ]:
gaussseidel_matriz_coef = np.array([[28,42,48],[23,50,45],[30,45,60]], dtype=float)
gaussseidel_matriz_constantes = np.array([102,95,117], dtype=float)
gaussseidel_resultado, erros, n = sistemaslineares_calcula_por_gaussseidel(gaussseidel_matriz_coef, gaussseidel_matriz_constantes, 1, 0.00001, 100)
imprimeResultados(gaussseidel_resultado)

Preço dos itens:
Cachorro-quente = 1.5
Pastel = 0.4
Batatas-fritas = 0.9


# Mais trabalho para o novo tesoureiro

Muito satisfeito com o trabalho que você apresentou a diretoria do **IFPB** solicitou, com o propósito de validar a metodologia utilizada para o cálculo, que você encontrasse o valor de cada salgado caso o montante arrecadado por cada barraca fosse conforme tabela abaixo:

Situação|Barraca do João|Barraca da Lucimara|Barraca da Bianca
-----|-----|-----|-----
1|150,00|108,00|215,00
2|65,00|72,00|48,00
3|123,00|76,00|49,00




## Situação 1:

Barraca|Arrecadação
-----|-----
João|150,00
Lucimara|108,00
Bianca|215,00

## Situação 2:

Barraca|Arrecadação
-----|-----
João|65,00
Lucimara|72,00
Bianca|48,00


## Situação 3:

Barraca|Arrecadação
-----|-----
João|123,00
Lucimara|76,00
Bianca|49,00


# Análise

Olhando os dados você percebe que quando você escreve o sistema de equações que a matriz de coeficientes é a mesma para todos as barracas, conforme solicitação da instituição, logo você lembra dos ensinamentos da disciplina de Cálculo Numérico, em especial, quando cursou com o professor @lacouth, e decide resolver os sistemas utilizando **Decomposição LU** 


Analisando os dados que a diretoria da instituição passou, você se lembra dos excelentes ensinamentos da disciplina de Cálculo Numérico, em especial, quando cursou com o professor @lacouth, e decide resolver os sistemas utilizando **Decomposição LU**, dessa forma agiliria bastante o processo para resolução desse sistema.

## A Decomposição LU


Deforma geral teremos um sistema da seguinte forma: $ [A].[X] = [B] $

Para utilizarmos a metodologia da **Decomposição LU**, primeiramente iremos transformar a matriz de coeficientes do nosso sistema em duas matrizes: uma matriz triangular superior e a outra uma triangular inferior com os elementos da diagonal com valor 1.

Chamaremos a matriz triangular superior de **U**, e a inferior de **L**.

Então, teremos: $ [L].[U].[X] = [B] $

Para resolvermos o sistema teremos duas partes:

* A primeira parte é a decomposição propriamente dita.
* A segunda parte é a resolução do seguinte sistema: 
$ \left\{\begin{array}
{rrr}
[L].[Z] & = & [B] \\
[U].[X] & = & [Z]
\end{array}
\right\}
$


A primeira equação conseguiremos encontrar a matriz [Z] e com ela encontraremos a matriz [X] na segunda equação.



#### Função: geraMatrizIdentidade(ordem):

Essa função gera uma matriz identidade de ordem X, fundamental para a decomposição LU.

In [ ]:
def geraMatrizIdentidade(ordem):
  I = np.ones((ordem, ordem))
  for linha in range (0, ordem):
    for coluna in range (0, ordem):
      if (linha == coluna):
        I[linha, coluna] = 1
      else:
        I[linha, coluna] = 0
  return I

#### Função: sistemalinear_decomporLU(matriz):

Esta função espera receber uma matriz de coeficientes e retornará duas matrizes: a primeira é uma matriz U do sistema, e a segunda é a matriz L.

In [ ]:
def sistemalinear_decomporLU(matriz):
  posPivo = 0
  row = 0
  col = 0
  multiply = []
  idxMultiply = 0;
  
  #rowPivo = 0
  #colPivo = 0
  
  # Prepara a matriz L
  matriz_l = geraMatrizIdentidade(np.shape(matriz)[0])
  
  
  # Laço para a posição do pivô  
  for posPivo in range (0, np.shape(matriz)[0] - 1 ):  
    # Coleta o pivô
    pivo = matriz[posPivo, posPivo]  
    #print("Pivô: {}".format(pivo))
    
    # Percorre as linhas da matriz abaixo do pivo para calcular o multiplixador
    for row in range (1+posPivo, np.shape(matriz)[0] ):
      # Calcula o multiplicador M
      multiply.append(matriz[row, posPivo] / pivo)
      #print("Multiplicador[{}]: {}".format(idxMultiply, multiply[idxMultiply]))
      #print("Linha:{} e Coluna: {}".format(row, col))
      
      
      # Percorre as colunas da linha após a posição do pivô
      for col in range (posPivo, np.shape(matriz)[1]):
        # Calcula o valor da nova linha
        matriz[row, col] = (matriz[row, col] - (matriz[posPivo, col] * multiply[idxMultiply])) 
      
      idxMultiply += 1
  
  # Monta a matriz L
  idxMultiply = 0;
  for linha in range(1, len(multiply)):
    for coluna in range(0, linha):
      #print("Coloca multiplicador em: [{}, {}]".format(linha, coluna))
      matriz_l[linha, coluna] = multiply[idxMultiply]
      idxMultiply += 1
      
  # Retorna a matriz após a etapa de eliminação      
  return matriz, matriz_l


#### Função: sistemalinear_substituicao_LU(matriz):

Esta função espera receber duas matrizes: uma matriz de coeficientes (L ou U) e uma matriz de constantes e retornará uma matriz com os valores para o X do sistema de equações lineares.

**Parâmetros**:

* **matrizcoef**: É a matriz de coeficiente (podendo ser L ou U)
* **matrizconst**: É a matriz de constantes
* **etapaU**: É um booleano para definir se a matriz de coeficiente é uma matriz L ou U. (verdadeiro significa que é U)

In [ ]:
def sistemalinear_substituicao_LU(matrizcoef, matrizconst, etapaU=True):
  x = []
  sum = []
  row = 0
  col = 0
  
  # Popula o array X de acordo com o tamanho da matriz do sistema 
  for idx in range(0, np.shape(matrizcoef)[0]):
    x.append(0)
    sum.append(0)
  if (etapaU==True):
    #print("Etapa U")
    # Percorre as linhas de forma decrescente
    for linha in range (np.shape(matrizcoef)[0]-1, -1, -1):
      # Faz o somatorio
      sum[linha] = 0
      for coluna in range (np.shape(matrizcoef)[0]):
        sum[linha] += matrizcoef[linha, coluna] * x[coluna]
        
      # Calcula o X
      #sum[linha] += matrizconst[linha]
      x[linha] = ( matrizconst[linha] - sum[linha] ) / matrizcoef[linha,linha]
  else:
    #print("Etapa L")
    # Percorre as linhas de forma decrescente
    for linha in range (0, np.shape(matrizcoef)[0]):
      # Faz o somatorio
      sum[linha] = 0
      for coluna in range (np.shape(matrizcoef)[0]):
        sum[linha] += matrizcoef[linha, coluna] * x[coluna]
        
      # Calcula o X
      #sum[linha] += matrizconst[linha]
      x[linha] = ( matrizconst[linha] - sum[linha] ) / matrizcoef[linha,linha]
      
  return x;

### Primeira Parte

Faremos a decomposição em duas matrizes: L e U, a partir da matriz de coeficiente.

In [ ]:
# Define a matriz de coeficientes
coeficientes = np.array([[28,42,48],[23,50,45],[30,45,60]], dtype=float)
#
matrizU, matrizL = sistemalinear_decomporLU(coeficientes)

print("Matriz L:")
print(matrizL)
print("")
print("Matriz U")
print(matrizU)

Matriz L:
[[1.000 0.000 0.000]
 [0.821 1.000 0.000]
 [1.071 0.000 1.000]]

Matriz U
[[28.000 42.000 48.000]
 [0.000 15.500 5.571]
 [0.000 0.000 8.571]]


### Segunda Parte

Iremos utilizar as matrizes L e U para encontrar a matriz Z e X para cada matriz de constantes contidas na tabela que foi passada pela instituição **IFPB**.

### Situação 1:

Barraca|Arrecadação
-----|-----
João|415,00
Lucimara|392,00
Bianca|487,50

In [ ]:
# Matriz de Constantes para a Situação 1
matriz_situacao_1 = np.array([415,392,487,5], dtype=float)

# Calcula a matriz Z
matriz_Z = sistemalinear_substituicao_LU(matrizL, matriz_situacao_1, False)
# Calcula a matriz X
matriz_X = sistemalinear_substituicao_LU(matrizU, matriz_Z, True)
imprimeResultados(matriz_X)

Preço dos itens:
Cachorro-quente = 4.069
Pastel = 1.521
Batatas-fritas = 4.942



### Situação 2:

Barraca|Arrecadação
-----|-----
João|504,00
Lucimara|484,00
Bianca|600,00




In [ ]:
# Matriz de Constantes para a Situação 2
matriz_situacao_2 = np.array([504,484,600], dtype=float)

# Calcula a matriz Z
matriz_Z = sistemalinear_substituicao_LU(matrizL, matriz_situacao_2, False)
# Calcula a matriz X
matriz_X = sistemalinear_substituicao_LU(matrizU, matriz_Z, True)
imprimeResultados(matriz_X)

Preço dos itens:
Cachorro-quente = 3.0
Pastel = 2.0
Batatas-fritas = 7.0


## Situação 3:

Barraca|Arrecadação
-----|-----
João|408,00
Lucimara|378,50
Bianca|480,00

In [ ]:
# Matriz de Constantes para a Situação 3
matriz_situacao_3 = np.array([408,378.5,480], dtype=float)

# Calcula a matriz Z
matriz_Z = sistemalinear_substituicao_LU(matrizL, matriz_situacao_3, False)
# Calcula a matriz X
matriz_X = sistemalinear_substituicao_LU(matrizU, matriz_Z, True)
imprimeResultados(matriz_X)

Preço dos itens:
Cachorro-quente = 4.5
Pastel = 1.0
Batatas-fritas = 5.0


# Conclusão

Todos os métodos utilizados na resolução desse sistema de equações lineares se mostraram competentes, porém, no quesito eficiência o método da decomposição LU se mostrou melhor que os demais, pois, re-utiliza a decomposição feita na primeira vez em todas as demais vezes que se precisar resolver o mesmo sistema com novos valores para a matriz de constantes.

Com base na suposição que a diretoria do **IFPB** trouxe para os valores arrecadados em cada barraca conforme tabela supra citada, o método da decomposição LU apenas precisou executar a etapa de substituição. Isso o torna mais eficiente se tivermos que fazer essa operação para n vezes.