In [1]:
import numpy as np
from scipy.linalg import solve_triangular
np.set_printoptions(formatter={'float': lambda x: "{:.4f}".format(x)})

In [2]:
def lu(M):
    L = np.zeros(M.shape)
    U = M.copy()
    P = np.identity(M.shape[0])
    
    passos = M.shape[0]-1
    for p in range(passos):
        pos = np.argmax(abs(U[p:,p]))+p
        
        if pos > p:
            U[[p,pos],:] = U[[pos,p],:]
            P[[p,pos],:] = P[[pos,p],:]
            L[[p,pos],:] = L[[pos,p],:]
        
        pivo = U[p,p]
        print(L)
        for i in range(p+1,U.shape[0]):
            m = U[i,p]/pivo
            U[i] = U[i] - U[p]*m
            L[i,p] = m
            
    for i in range(M.shape[0]):
        L[i,i] = 1
            
    return L,U,P

In [3]:
A = np.array([[25,5,1],[64,8,1],[144,12,1]],dtype = float)
l,u,p = lu(A)
print(l)
np.dot(l,u)

[[0.0000 0.0000 0.0000]
 [0.0000 0.0000 0.0000]
 [0.0000 0.0000 0.0000]]
[[0.0000 0.0000 0.0000]
 [0.1736 0.0000 0.0000]
 [0.4444 0.0000 0.0000]]
[[1.0000 0.0000 0.0000]
 [0.1736 1.0000 0.0000]
 [0.4444 0.9143 1.0000]]


array([[144.0000, 12.0000, 1.0000],
       [25.0000, 5.0000, 1.0000],
       [64.0000, 8.0000, 1.0000]])

In [ ]:
def solve_lu(A,B):
    L,U,P = lu(A)
    Z = np.zeros(B.shape)
    X = np.zeros(B.shape)
    Z = solve_triangular(L,np.dot(P,B), lower = True)
    X = solve_triangular(U,Z)
    return X

In [ ]:
A = np.array([[25,5,1],[64,8,1],[144,12,1]],dtype = float)
B = np.array([106.8,177.2,279.2])
solve_lu(A,B)

In [ ]:
A[:,0]

In [ ]:
np.argmax(A[:,0])

In [ ]:
def inv_lu(M):
    L,U,P = lu(M)
    Z = np.zeros(M.shape[0])
    M_inv = np.zeros(M.shape)
    for i in range(M.shape[0]):
        Z = solve_triangular(L,P[:,i], lower=True)
        M_inv[:,i] = solve_triangular(U,Z)
    return M_inv

In [ ]:
A = np.array([[25,5,1],[64,8,1],[144,12,1]],dtype = np.float)
A_inv = inv_lu(A)
print(A_inv)

In [ ]:
np.dot(A,A_inv)

In [ ]:
def gauss_seidel(A,B,chutes,tolerancia, max_it):
    X = np.array(chutes,dtype=float)
    erros = np.zeros(A.shape[0])
    for k in range(max_it):
        X_ant = X.copy()
        for i in range(A.shape[0]):
            X[i] = B[i]
            for j in range(A.shape[1]):
                if j!=i:
                    X[i] -= A[i,j]*X[j]
            X[i] /= A[i,i]
            erros[i] = abs((X[i]-X_ant[i])/X[i])*100
        if max(erros) < tolerancia:
            return X
    return X    

In [ ]:
A = np.array([[12,3,-5],[1,5,3],[3,7,13]], dtype=float)
B = np.array([1,28,76])
gauss_seidel(A,B,[0,0,0],0.0001,100)