# Métodos Numéricos 2019.1
## Patric Lacouth
### lacouth@gmail.com

## NumPy

* O cálculo numérico envolve muita matemática matricial e é importante que você entenda o básico antes de mergulhar na construção dos seus algoritmos.

* Essas lições fornecem uma breve atualização sobre o que você precisa saber para este curso, além de algumas orientações sobre como usar a biblioteca NumPy para trabalhar de forma eficiente com matrizes no Python.

* Link para a página da [NumPy](http://www.numpy.org/)

# Dimensões

* nós vamos fazer muitas contas com muitos dados.

* primeiro temos que entender como representamos esses dados.




# As formas que os dados podem assumir

* um número representando a altura de uma pessoa em centímetros.

![](altura.png)

# As formas que os dados podem assumir

* Ou uma série de números representando várias características dessa pessoa, como altura, peso e idade.

![](girl_vector.png)

# As formas que os dados podem assumir

* Ou talvez uma imagem dessa pessoa representada como uma grade, com linhas e colunas de pixels individuais.

![](girl_photo.png)

# As formas que os dados podem assumir

* Uma forma possível de representar um pixel nessa imagem pode usar 3 números, um para cada um dos canais de cor, vermelho, azul e verde.

![](girl_pixel.png)

# Escalares

## <pre> 1      2.4        -0.3 </pre>

### escalares têm dimensão zero

# Vetores

![](vetor_linha_coluna.png)

* vetores têm uma dimensão: comprimento (length)

# Vetores

* o valores da altura, peso e idade podem ser representado através de vetor linha

![](girl_row_vector.png)

# Matrizes

* Descrevemos a forma de uma matriz de acordo com seu número de linhas e colunas.

![](girl_matrix.png)

# Tensores

* O termo tensor pode se referir a qualquer conjunto de valores n-dimensionais.

![](tensor.png)

# Tensores 

* O problema é que dados com dimensões mais altas podem ser difíceis de visualizar.

![](3d_matrix.png)

* Para 3 dimensões, pensamos em uma pilha de matrizes,

# Tensores

* Podemos então representar uma imagem RGB como um tensor de três dimensões.

![](girl_3d.png)

# Tensores 

* O problema é que dados com dimensões mais altas podem ser difíceis de visualizar.

![](4d_matrix.png)

* E, para 4 dimensões, pensamos em uma matriz em que cada uma das entradas é uma matriz,


# Simplificando

* Na maioria dos casos vamos considerar que tudo pode ser representado como uma matriz.

![](matrixes.png)

# Matrizes e índices

* Para utilizar os elementos de uma matriz precisamos saber os seus índices

![](matrix_indices.png)

# Matrizes e índices

* Mas temos que lembrar que computacionalmente começamos a contar do ZERO.

![](matrix_indices_zero.png)

# Introdução ao NumPy

* O Python é conveniente, mas também pode ser lento. No entanto, ele permite que você acesse bibliotecas que executam códigos mais rápidos escritos em linguagens como C.

* A NumPy é uma dessas bibliotecas: fornece alternativas rápidas para operações matemáticas em Python e foi projetada para funcionar eficientemente com grupos de números - como matrizes.

* NumPy é uma biblioteca enorme e vamos apenas arranhar a superfície dela aqui.

# Importando NumPy

* Ao importar a biblioteca NumPy, a convenção que você verá usada com mais freqüência - incluindo aqui - é nomear np, assim:

In [42]:
import numpy as np 

Agora você pode usar a biblioteca prefixando os nomes de funções e tipos com `np`

O conjunto completo de funções em numpy é muito longo para ser impresso em sua totalidade.
A lista a seguir está limitada às funções mais usadas.

`[’complex’, ’float’, ’abs’, ’append’, arccos’,
’arccosh’, ’arcsin’, ’arcsinh’, ’arctan’, ’arctan2’,
’arctanh’, ’argmax’, ’argmin’, ’cos’, ’cosh’, ’diag’,
’diagonal’, ’dot’, ’e’, ’exp’, ’floor’, ’identity’,
’inner, ’inv’, ’log’, ’log10’, ’max’, ’min’,
’ones’, ’outer’, ’pi’, ’prod’ ’sin’, ’sinh’, ’size’,
’solve’, ’sqrt’, ’sum’, ’tan’, ’tanh’, ’trace’,
’transpose’, ’vectorize’,’zeros’]`

# Tipos e formas de dados

* A maneira mais comum de trabalhar com números no NumPy é através de objetos ndarray. 
* Eles são semelhantes às listas do Python, mas podem ter qualquer número de dimensões. 
* Além disso, o ndarray suporta operações matemáticas rápidas, o que é exatamente o que queremos.

# Escalares

* Os escalares no NumPy estão um pouco mais desenvolvidos do que no Python. 

* Em vez dos tipos básicos do Python, como int, float, etc., o NumPy permite especificar tipos com tamanhos diferentes. Então, em vez do `int` do Python, você tem acesso a tipos como `uint8`, `int8`, `uint16`, `int16` e assim por diante. 

* [Tipos NumPy](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html)


# Escalares

* E quando você criar um array NumPy, você pode especificar o tipo - mas cada item no array devem ter o mesmo tipo. 

* A este respeito, os arrays Numpy são mais como arrays C/C++ do que listas de Python.

In [12]:
s = np.array(5)
s

array(5)

In [14]:
x = s + 3
x

8

# Vetores

Para criar um vetor, você passaria uma lista do Python para a função `array`, assim:

In [16]:
v = np.array([1,2,3])
v

array([1, 2, 3])

In [18]:
v.shape

(3,)

In [19]:
v[1]

2

In [20]:
v[1:]

array([2, 3])

In [21]:
v[-1]

3

Agora que há um número, você pode ver que a forma é uma tupla com os tamanhos de cada uma das dimensões do ndarray. Para escalares era apenas uma tupla vazia, mas os vetores têm uma dimensão, então a tupla inclui um número e uma vírgula. (O Python não entende (3) como uma tupla com um item, por isso requer a vírgula. Você pode ler mais sobre as tuplas [aqui](https://docs.python.org/3/tutorial/datastructures.html#tuples-and-sequences))

# Matrizes

Você cria matrizes usando a função array do NumPy, da mesma forma que vocês fez para vetores. No entanto, em vez de apenas passar em uma lista, você precisa fornecer uma lista de listas, onde cada lista representa uma linha. Então, para criar uma matriz 3x3 contendo os números de um a nove, você poderia fazer isso:

In [22]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
m.shape

(3, 3)

# Operações com elementos (Element-wise)
> Tratar os itens na matriz individualmente e execute a operação em cada um deles.



# Aplicação real

* Suponha que você precise mudar a escala do canal vermelho de uma imagem
    * Transformar os valores de 0 - 255 para 0 - 1

# Aplicação real

![red_channel](red_channel.png)

# Aplicação real

![red_channel2](red_channel_2.png)

# Operações com elementos (Element-wise)

Suponha que você tenha uma lista de números e queira adicionar 5 a todos os itens da lista. Sem o NumPy, você pode fazer algo assim:

In [31]:
vetor = [1,2,3,4,5]
for i in range(len(vetor)):
    vetor[i] += 5

vetor

[6, 7, 8, 9, 10]

### Com o NumPy

In [28]:
vetor = [1,2,3,4,5]
vetor = np.array(vetor)
vetor += 5
vetor

array([ 6,  7,  8,  9, 10])

# Operações com elementos (Element-wise)

> As mesmas funções e operadores que trabalham com escalares e matrizes também funcionam com outras dimensões. Você só precisa se certificar de que os itens em que você realiza a operação tenham formas compatíveis.

![matrix_sum](matriz_sum.png)

![matriz_sum2](matrix_sum2.png)

## Com o NumPy

In [32]:
a = np.array([[1,3],[5,7]])
a

array([[1, 3],
       [5, 7]])

In [33]:
b = np.array([[2,4],[6,8]])
b

array([[2, 4],
       [6, 8]])

In [34]:
a + b

array([[ 3,  7],
       [11, 15]])

E se você tentar trabalhar com formas incompatíveis,

In [35]:
a = np.array([[1,3],[5,7]])
a

array([[1, 3],
       [5, 7]])

In [36]:
c = np.array([[2,3,6],[4,5,9],[1,8,7]])
c

array([[2, 3, 6],
       [4, 5, 9],
       [1, 8, 7]])

In [37]:
a.shape

(2, 2)

In [38]:
c.shape

(3, 3)

In [39]:
a + c

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

# O produto de matrizes


$$
\left[ \begin{matrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 
\end{matrix} \right]
%
\dot
%
\left[ \begin{matrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 
\end{matrix} \right]
%
=
%
\left[ \begin{matrix}
30 & 36 & 42 \\
66 & 81 & 96 \\
102 & 126 & 150 
\end{matrix} \right]
$$


## Lembretes importantes sobre a multiplicação de matrizes

* O número de colunas na matriz esquerda deve ser igual ao número de linhas na matriz direita.


In [44]:
a = np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

In [45]:
b = np.array([[1,2],[3,4],[5,6]])
b.shape

(3, 2)

* A ordem é importante. Multiplicar A • B não é o mesmo que multiplicar B • A.
* A matriz de respostas sempre tem o mesmo número de linhas que a matriz da esquerda e o mesmo número de colunas que a matriz da direita.

# O Produto de matrizes no NumPy

Para encontrar o produto da matriz, use a função `matmul` do NumPy.

Se você tem dimensões compatíveis, então é simples assim:

In [51]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [52]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [53]:
c = np.matmul(a, b)
c

array([[ 70,  80,  90],
       [158, 184, 210]])

## Matriz Transposta

Obter a transposição de uma matriz é realmente fácil no NumPy. Basta acessar seu atributo T. Há também uma função transpose () que retorna a mesma coisa, mas você raramente verá isso em qualquer lugar porque digitar T é muito mais fácil. :)

In [46]:
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
m.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

O NumPy faz isso sem realmente mover nenhum dado na memória - ele simplesmente altera a maneira como indexa a matriz original - por isso é bastante eficiente.

In [49]:
m_t = m.T
m_t[3][1] = 200
m_t

array([[  1,   5,   9],
       [  2,   6,  10],
       [  3,   7,  11],
       [  4, 200,  12]])

In [50]:
m

array([[  1,   2,   3,   4],
       [  5,   6,   7, 200],
       [  9,  10,  11,  12]])

# That's all for now!