<a href="https://colab.research.google.com/github/lacouth/metodos_numericos/blob/master/sistemas_lineares/exercicios_sistemas_lineares.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sistemas Lineares - Exercícios

In [0]:
import numpy as np
np.set_printoptions(formatter={'float': lambda x: "{:.4f}".format(x)}) # configura a impressão dos floats

## Dicas Numpy

### Criar um matriz

In [0]:
M = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]], dtype=float)
M

array([[1.0000, 2.0000, 3.0000, 4.0000],
       [5.0000, 6.0000, 7.0000, 8.0000],
       [9.0000, 10.0000, 11.0000, 12.0000],
       [13.0000, 14.0000, 15.0000, 16.0000]])

### Selecionar apenas uma linha

In [0]:
M[1]

array([5.0000, 6.0000, 7.0000, 8.0000])

### Selecionar apenas uma coluna

In [0]:
M[:,1]

array([2.0000, 6.0000, 10.0000, 14.0000])

### Selecionar a última linha ou coluna

In [0]:
M[-1]

array([13.0000, 14.0000, 15.0000, 16.0000])

In [0]:
M[:,-1]

array([4.0000, 8.0000, 12.0000, 16.0000])

### Selecionar um trecho de uma linha ou coluna

In [0]:
M

array([[1.0000, 2.0000, 3.0000, 4.0000],
       [5.0000, 6.0000, 7.0000, 8.0000],
       [9.0000, 10.0000, 11.0000, 12.0000],
       [13.0000, 14.0000, 15.0000, 16.0000]])

In [0]:
M[1,1:3]

array([6.0000, 7.0000])

In [0]:
M[1:3,1]

array([6.0000, 10.0000])

### Multiplicar uma linha por uma constante

In [0]:
M

array([[1.0000, 2.0000, 3.0000, 4.0000],
       [5.0000, 6.0000, 7.0000, 8.0000],
       [9.0000, 10.0000, 11.0000, 12.0000],
       [13.0000, 14.0000, 15.0000, 16.0000]])

In [0]:
l = M[0]*2
l

array([2.0000, 4.0000, 6.0000, 8.0000])

In [0]:
c = M[:,0]*2
c

array([2.0000, 10.0000, 18.0000, 26.0000])

### Subtrair um linha pela outra

In [0]:
M

array([[1.0000, 2.0000, 3.0000, 4.0000],
       [5.0000, 6.0000, 7.0000, 8.0000],
       [9.0000, 10.0000, 11.0000, 12.0000],
       [13.0000, 14.0000, 15.0000, 16.0000]])

In [0]:
linha = M[2]-M[1]
linha

array([4.0000, 4.0000, 4.0000, 4.0000])

In [0]:
coluna = M[:,2]-M[:,1]
coluna

array([1.0000, 1.0000, 1.0000, 1.0000])

### Encontrar o maior valor em uma linha/coluna

In [0]:
np.max(M[0])

4.0

In [0]:
np.max(M[:,0])

13.0

### Encontrar o *índice* do maior elemento

In [0]:
M

array([[1.0000, 2.0000, 3.0000, 4.0000],
       [5.0000, 6.0000, 7.0000, 8.0000],
       [9.0000, 10.0000, 11.0000, 12.0000],
       [13.0000, 14.0000, 15.0000, 16.0000]])

In [0]:
np.argmax(M[0])

3

In [0]:
np.argmax(M[:,0])

3

## Exercício 1
### Encontre a solução do seguinte sistema

$$ 25x_1+5x_2+x_3 = 106.8$$
$$ 64x_1+8x_2+x_3 = 177.2$$
$$ 144x_1+12x_2+x_3 = 279.2$$

utilizando o método de Gauss ingênuo

## Exercício 2
### Encontre a solução do seguinte sistema

$$      2x_2+3x_3 = 8$$
$$ 4x_1+6x_2+7x_3 = -3$$
$$ 2x_1+3x_2+6x_3 = 5$$

utilizando o método de Gauss ingênuo

## Exercício 3
### Encontre a solução do seguinte sistema

$$      2x_2+3x_3 = 8$$
$$ 4x_1+6x_2+7x_3 = -3$$
$$ 2x_1+3x_2+6x_3 = 5$$

utilizando o método de Gauss com pivotação parcial

## Exercício 4
Resolva o sistema abaixo utilizando o método de Gauss e o método da pivotação parcial. Compare com a solução exata $ x = [10,1]$:

$$0.003x_1 + 59.14x_2 = 59.17$$
$$-5.291x_1 - 6.130x_2 = 49.78$$

comente sobre o resultado

## Exercício 5
Resolva os sistemas utilizando um método direto e o método de Gauss-Seidel

a. 
    $$8.7x_1 + 3x_2 + 9.3x_3 + 11x_4 = 16.4$$
    $$24.5x_1 - 8.8x_2 + 11.5x_3 - 45.1x_4 = -49.7$$
    $$52.3x_1 - 84x_2 - 23.5x_3 + 11.4x_4 = -80.8$$
    $$21x_1 - 81x_2 - 13.2x_3 + 21.5x_4 = -106.3$$

b.

$$3x_1 + 7x_2 + 13x_3 = 76$$
$$12x_1 + 3x_2 - 5x_3 = 1$$
$$x_1 + 5x_2 + 3x_3 = 28$$

c.
    $$1x_2 + 3x_3 + 2x_4 + 4x_5 = 3$$
    $$8x_1 - 2x_2 + 9x_3 - 1x_4 + 2x_5 = -5$$
    $$5x_1 + x_2 + x_3 + 7x_4 + 2x_5 = 6$$
    $$-2x_1 + 4x_2 + 5x_3 + 1x_4 = -1$$
    $$7x_1 - 3x_2 + 2x_3 - 4x_4 + 1x_5 = -5$$


## Exercício 6

Uma barra linear de metal de um metro de comprimento é mantida a 0 graus Celsius em um extremo e a 128 graus Celsius no outro. Desejamos determinar a temperatura da barra a cada 20cm . Denominando de T0 = 0 a temperatura de um extremo, de T5 = 128 a temperatura no outro extremo e de T1, T2, T3 e T4 a temperatura nos pontos interiores e sabendo que a temperatura em cada ponto interior é igual a média aritmética da temperatura de seus dois pontos vizinhos.

    Determine através de um método de resolução de sistemas lineares os valores de T1, T2, T3 e T4

## Exercício 7

Calcule a inversa das matrizes abaixo utilizando dois métodos de resolução de sistemas lineares

a.

$$A = \begin{bmatrix}
    8 & 5 & 1 \\
    3 & 7 & 4\\
    2 & 3 & 9 
\end{bmatrix}$$

b.
$$A = \begin{bmatrix}
        1 & 6 & 4 \\
        2 & -3 & 1\\
        5 & 5 & 8 
\end{bmatrix}$$

## Exercício 8

Calcular as tensões nos nós do circuito elétrico abaixo:

![](https://github.com/lacouth/metodos_numericos/blob/master/sistemas_lineares/circuito.png?raw=1)

## Modelagem matemática

Pela lei de *Kirchhoff*, a soma das correntes que passam em cada nó do circuito é nula. Pela lei de *Ohm* a corrente elétrica que flui do nó *j* para o nó *k* de um circuito é 

$$I_{jk} = \frac{V_j-V_k}{R_{jk}}$$

sendo $V_j$ e $V_k$ as tensões nos nós $j$  e $k$, respectivamente, e $R_{jk}$ a resistência no arco _jk_. A corrente $I$ é expressa em ampères e a resistência $R$, em ohms. As duas leis combinadas permitem o cálculo da tensão em cada nó do circuito.

No nó 1, pela lei de _Kirchoff_,

$$I_{A1} + I_{21} + I_{31} + I_{41} = 0 $$

Utilizando a lei de _Ohm_, 

$$ \frac{0-V_1}{1} + \frac{V_2-V_1}{1} + \frac{V_3-V_1}{2} + \frac{V_4-V_1}{2} = 0 $$

simplificando:

$$ -6V_1 + 2V_2 + V_3 + V_4 = 0$$


Determinando as equações dos nós 2, 3 e 4, constrói-se um sistema de equações lineares. O vetor solução fornece a tensão em cada nó do circuito elétrico.

Construa o resto do sistema e utilizando dois métodos de resolução numérica encontre as tensões em cada um dos nós.