# Sistemas Lineares

In [2]:
import numpy as np
np.set_printoptions(formatter={'float': lambda x: "{:.4f}".format(x)}) # configura a impressão dos floats

## Dicas Numpy

### Criar um matriz

In [16]:
M = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
M

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### Selecionar apenas uma linha

In [17]:
M[1]

array([5, 6, 7, 8])

### Selecionar apenas uma coluna

In [18]:
M[:,1]

array([ 2,  6, 10, 14])

### Selecionar a última linha ou coluna

In [19]:
M[-1]

array([13, 14, 15, 16])

In [20]:
M[:,-1]

array([ 4,  8, 12, 16])

### Selecionar um trecho de uma linha ou coluna

In [36]:
M

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [21]:
M[1,1:3]

array([6, 7])

In [22]:
M[1:3,1]

array([ 6, 10])

### Multiplicar uma linha por uma constante

In [35]:
M

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [23]:
l = M[0]*2
l

array([2, 4, 6, 8])

In [25]:
c = M[:,0]*2
c

array([ 2, 10, 18, 26])

### Subtrair um linha pela outra

In [34]:
M

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [27]:
linha = M[2]-M[1]
linha

array([4, 4, 4, 4])

In [28]:
coluna = M[:,2]-M[:,1]
coluna

array([1, 1, 1, 1])

### Encontrar o maior valor em uma linha/coluna

In [29]:
np.max(M[0])

4

In [30]:
np.max(M[:,0])

13

### Encontrar o *índice* do maior elemento

In [33]:
M

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [31]:
np.argmax(M[0])

3

In [32]:
np.argmax(M[:,0])

3

## Exercício 1
### Encontre a solução do seguinte sistema

$$ 25x_1+5x_2+x_3 = 106.8$$
$$ 64x_1+8x_2+x_3 = 177.2$$
$$ 144x_1+12x_2+x_3 = 279.2$$

utilizando o método de Gauss ingênuo

## Exercício 2
### Encontre a solução do seguinte sistema

$$      2x_2+3x_3 = 8$$
$$ 4x_1+6x_2+7x_3 = -3$$
$$ 2x_1+3x_2+6x_3 = 5$$

utilizando o método de Gauss ingênuo

## Exercício 3
### Encontre a solução do seguinte sistema

$$      2x_2+3x_3 = 8$$
$$ 4x_1+6x_2+7x_3 = -3$$
$$ 2x_1+3x_2+6x_3 = 5$$

utilizando o método de Gauss com pivotação parcial

## Exercício 4
Resolva o sistema abaixo utilizando o método de Gauss e o método da pivotação parcial. Compare com a solução exata $ x = [10,1]$:

$$0.003x_1 + 59.14x_2 = 59.17$$
$$-5.291x_1 - 6.130x_2 = 49.78$$

comente sobre o resultado