<a href="https://colab.research.google.com/github/lacouth/metodos_20191/blob/master/matrizes/exemplo_gauss_ingenuo_for%C3%A7a_bruta.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
np.set_printoptions(formatter={'float': lambda x: "{:.4f}".format(x)})

In [13]:
AB = np.array([[-4,2,0,1,-100],[1,-2,1,0,0],[0,2,-3,1,0],[5,0,5,-12,0]],dtype = float)
AB

array([[-4.0000, 2.0000, 0.0000, 1.0000, -100.0000],
       [1.0000, -2.0000, 1.0000, 0.0000, 0.0000],
       [0.0000, 2.0000, -3.0000, 1.0000, 0.0000],
       [5.0000, 0.0000, 5.0000, -12.0000, 0.0000]])

# Passo 1

In [14]:
pivo = AB[0,0]
m1 = AB[1,0]/pivo
AB[1,:] = AB[1,:]-AB[0,:]*m1
AB

array([[-4.0000, 2.0000, 0.0000, 1.0000, -100.0000],
       [0.0000, -1.5000, 1.0000, 0.2500, -25.0000],
       [0.0000, 2.0000, -3.0000, 1.0000, 0.0000],
       [5.0000, 0.0000, 5.0000, -12.0000, 0.0000]])

In [15]:
m3 = AB[3,0]/pivo
AB[3,:] = AB[3,:]-AB[0,:]*m3
AB

array([[-4.0000, 2.0000, 0.0000, 1.0000, -100.0000],
       [0.0000, -1.5000, 1.0000, 0.2500, -25.0000],
       [0.0000, 2.0000, -3.0000, 1.0000, 0.0000],
       [0.0000, 2.5000, 5.0000, -10.7500, -125.0000]])

# 2 passo

In [16]:
pivo = AB[1,1]
m4 = AB[2,1]/pivo
AB[2,:] = AB[2,:] - AB[1,:]*m4
AB

array([[-4.0000, 2.0000, 0.0000, 1.0000, -100.0000],
       [0.0000, -1.5000, 1.0000, 0.2500, -25.0000],
       [0.0000, 0.0000, -1.6667, 1.3333, -33.3333],
       [0.0000, 2.5000, 5.0000, -10.7500, -125.0000]])

In [17]:

m5 = AB[3,1]/pivo
AB[3,:] = AB[3,:] - AB[1,:]*m5
AB

array([[-4.0000, 2.0000, 0.0000, 1.0000, -100.0000],
       [0.0000, -1.5000, 1.0000, 0.2500, -25.0000],
       [0.0000, 0.0000, -1.6667, 1.3333, -33.3333],
       [0.0000, 0.0000, 6.6667, -10.3333, -166.6667]])

In [18]:
pivo = AB[2,2]
m6 = AB[3,2]/pivo
AB[3,:] = AB[3,:] - AB[2,:]*m6
AB

array([[-4.0000, 2.0000, 0.0000, 1.0000, -100.0000],
       [0.0000, -1.5000, 1.0000, 0.2500, -25.0000],
       [0.0000, 0.0000, -1.6667, 1.3333, -33.3333],
       [0.0000, 0.0000, 0.0000, -5.0000, -300.0000]])

In [19]:
V4 = AB[3,-1]/AB[3,-2]
V4

59.99999999999999

In [21]:
V3 = (AB[2,-1] - V4*AB[2,-2])/AB[2,2]
V3

67.99999999999999

In [22]:
AB

array([[-4.0000, 2.0000, 0.0000, 1.0000, -100.0000],
       [0.0000, -1.5000, 1.0000, 0.2500, -25.0000],
       [0.0000, 0.0000, -1.6667, 1.3333, -33.3333],
       [0.0000, 0.0000, 0.0000, -5.0000, -300.0000]])

In [30]:
V2 = (AB[1,-1] - AB[1,-2]*V4 - V3)/AB[1,1]
V2

71.99999999999999

In [29]:
V1 = (AB[0,-1] - AB[0,-2]*V4 - AB[0,-3]*V2)/AB[0,0]
V1

40.0