# Resolução de Sistemas Lineares

No módulo anterior, nós determinamos o valor de $x$ que satisfaz uma simples equação $f(x) = 0$. Agora, vamos tratar o caso de determinar os valores de $x_1, x_2, \dots , x_n$ que simultaneamente satisfaça o conjunto de equações:

$$f_1(x_1, x_2, \dots , x_n) = 0$$
$$f_2(x_1, x_2, \dots , x_n) = 0$$
$$\vdots$$
$$f_n(x_1, x_2, \dots , x_n) = 0$$

Esse conjunto de equações podem ser escritas em forma matricial de um sistema de equações lineares:

$$a_{11}x_1 + a_{12}x_2 + \dots a_{1n}x_n = b_1$$
$$a_{21}x_1 + a_{22}x_2 + \dots a_{2n}x_n = b_2$$
$$ \vdots $$
$$a_{n1}x_1 + a_{n2}x_2 + \dots a_{nn}x_n = b_n$$

onde os $a$ são os coeficiente, os $b$ as constantes, os $x$ são as icógnitas, e $n$ o número de equações;

## Representando um sistema linear na forma matricial

Deve ser claro que matrizes irão prover uma forma simples de representar um sistema de equações lineares. Por exemplo, um sistema 3 $\times$ 3:

$$a_{11}x_1 + a_{12}x_2 + a_{13}x_n = b_1$$
$$a_{21}x_1 + a_{22}x_2 + a_{23}x_n = b_2$$
$$a_{31}x_1 + a_{32}x_2 + a_{33}x_n = b_3$$

pode ser expresso como

$$[A][x] = [b]$$

onde $[A]$ é a matriz de coeficientes:

$$[A]= 
\left[ \begin{matrix}
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23}\\
a_{31} & a_{32} & a_{33}
\end{matrix} \right]
$$

$[b]$ é o vetor coluna de constantes

$$[b]= 
\left[ \begin{matrix}
b_{1}\\
b_{2}\\
b_{3}
\end{matrix} \right]
$$

e $[x]$ é o vetor coluna de icógnitas.

$$[x]= 
\left[ \begin{matrix}
x_{1}\\
x_{2}\\
x_{3}
\end{matrix} \right]
$$

## O método de Gauss ingênuo

O método de Gauss ingênuo é dividido em duas etapas:

1. **Eliminação**: essa fase é projetada para reduzir o conjunto de equações a um sistema triangular superior equivalente ao sistema original.

2. **Substituição**: com um sistema triangular agora é possível fazer uma série de substituições diretas para obter as icógnitas do sistema.

A figura abaixo ilustra os dois passos

![](gauss_steps.png)

# Exemplo

Dadas as equações abaixo encontre as icógnitas que satisfazem o sistema:

$$25x_1 + 5x_2 + x_3 = 106.8$$
$$64x_1 + 8x_2 + x_3 = 177.2$$
$$144x_1 + 12x_2 + x_3 = 279.2$$

representando matricialmente:

$$\left[ \begin{matrix}
25 & 5 & 1 \\
64 & 8 & 1\\
144 & 12 & 1
\end{matrix} \right]
\left[ \begin{matrix}
x_{1}\\
x_{2}\\
x_{3}
\end{matrix} \right]
=
\left[ \begin{matrix}
106.8\\
177.2\\
279.2
\end{matrix} \right]
$$

como vamos fazer operações com as matrizes $[A]$ e $[b]$ no python podemos representar as duas matrizes através de uma matriz estendida que contém todos os valores

$$[AB] = \left[ \begin{matrix}
25 & 5 & 1 & | & 106.8\\
64 & 8 & 1 & | & 177.2\\
144 & 12 & 1 & | & 279.2
\end{matrix} \right]$$

## Representando o sistema no python



In [1]:
import numpy as np
np.set_printoptions(formatter={'float': lambda x: "{:.2f}".format(x)})

In [3]:
AB = np.array([[25,5,1,106.8],[64,8,1,177.2],[144,12,1,279.2]])
AB

array([[25.00, 5.00, 1.00, 106.80],
       [64.00, 8.00, 1.00, 177.20],
       [144.00, 12.00, 1.00, 279.20]])

### Eliminação: Selecionando o primeiro pivô

Precisamos "zerar" os elementos abaixo do primeiro elemento da primeira coluna, para isso escolhemos o elemento $a_{11}$ como sendo o pivô que irá gerar o multiplicadores

In [4]:
pivo = AB[0,0]
pivo

25.0

Determinamos o primeiro multiplicador m1 como sendo o elemento que queremos zerar dividido pelo nosso pivô

In [5]:
m1 = AB[1,0]/pivo
m1

2.56

Para zerar o elemento abaixo do pivô iremos subtrair a sua linha pela linha do pivô multiplicada por m1

In [6]:
AB[1,:] = AB[1,:] - AB[0,:]*m1
AB

array([[25.00, 5.00, 1.00, 106.80],
       [0.00, -4.80, -1.56, -96.21],
       [144.00, 12.00, 1.00, 279.20]])

Para zerar o próximo elemento da coluna, precisamos de um novo multiplicador, m2, que será o próprio elemento dividido pelo pivô

In [7]:
m2 = AB[2,0]/pivo
m2

5.76

Repetimos o processo de subtrair a linha na qual desejamos zerar o elemento pela linha do pivô multiplicada por m2

In [8]:
AB[2,:] = AB[2,:] - AB[0,:]*m2
AB

array([[25.00, 5.00, 1.00, 106.80],
       [0.00, -4.80, -1.56, -96.21],
       [0.00, -16.80, -4.76, -335.97]])

## Eliminação: selecionando o segundo pivô

Depois de "eliminar" os elementos da primeira coluna temos que continuar a eliminação na segunda coluna. O pivô agora passa a ser o elemento $a_{22}$ 

In [9]:
pivo = AB[1,1]
pivo

-4.800000000000001

Nesta coluna temos que realizar apenas a eliminação de um elemento abaixo do pivô, repetimos o mesmo processo anterior, calculamos um multiplicador m3 a partir da divisão do elemento a ser zerado pelo pivô

In [10]:
m3 = AB[2,1]/pivo
m3

3.499999999999999

Com o multiplicador realizamos a operação na linha a ser modificada

In [11]:
AB[2,:] = AB[2,:] - AB[1,:]*m3
AB

array([[25.00, 5.00, 1.00, 106.80],
       [0.00, -4.80, -1.56, -96.21],
       [0.00, 0.00, 0.70, 0.76]])

Obtemos assim um sistema triangular superior que pode ser resolvido com substituições diretas

## Substituição: encontrando x3

Para encontrar $x_3$ precisamos apenas resolver a equação representada pela última linha do sistema

In [12]:
x = np.zeros(3)
x

array([0.00, 0.00, 0.00])

In [14]:
x[2] = AB[2,3]/AB[2,2]
x

array([0.00, 0.00, 1.09])

Com o valor de $x_3$ definido podemos encontrar $x_2$

In [15]:
x[1] = (AB[1,3] - AB[1,2]*x[2])/AB[1,1]
x

array([0.00, 19.69, 1.09])

Agora com os dois valores de x podemos encontrar $x_1$

In [18]:
x[0] = (AB[0,3] - AB[0,2]*x[2] - AB[0,1]*x[1])/AB[0,0]
x

array([0.29, 19.69, 1.09])

## Verificando a resposta

Uma forma de testar se a resposta obtida está correta é fazer o produto de cada linha da matriz de coeficientes com o vetor de icógnitas e verificar se o resultado é igual ao vetor de constantes. 

**Primeira linha**

In [25]:
M = np.array([[25,5,1.],[64,8,1],[144,12,1]])
C = np.array([106.8, 177,2, 279.2])
M

array([[25.00, 5.00, 1.00],
       [64.00, 8.00, 1.00],
       [144.00, 12.00, 1.00]])

In [27]:
np.dot(M[0,:],x)

106.8

**Segunda linha**

In [28]:
np.dot(M[1,:],x)

177.19999999999996

**Terceira Linha**

In [29]:
np.dot(M[2,:],x)

279.19999999999993

# Exercício

1. Crie uma função que receba uma matriz estendida [AB] e retorne uma matriz triangular superior

2. Crie uma função que receba uma matriz triangular superior estendida e retorne um vetor solução.