$$ x_2 = \frac{(-10 + x_1 - x_3 )}{-4}  $$

In [1]:
import numpy as np

In [2]:
A = np.array([[3,1,-1],
              [-1, -4 , 1],
              [1, -2, -5]
             ], dtype = float)
A

array([[ 3.,  1., -1.],
       [-1., -4.,  1.],
       [ 1., -2., -5.]])

In [5]:
diag = np.diag(np.abs(A))
diag

array([3., 4., 5.])

In [10]:
soma_linha = np.sum(np.abs(A),axis = 1) - diag
soma_linha

array([2., 2., 3.])

In [12]:
np.all(diag > soma_linha)

True

# Exemplo


$$\left\{\begin{matrix}
3x_1 & + & x_2 & - & x_3 & = & 2 \\ 
-x_1 & - &4x_2 & + & x_3 & = & -10 \\ 
x_1 & - & 2x_2 & - & 5x_3 & = & 10 
\end{matrix}\right.$$

In [16]:
x = np.array([0,0,0], dtype = float)
erros = []
for i in range(100):
    x_anterior = x.copy()
    x[0] = (2 - x[1] + x[2]) / 3
    x[1] = (-10 + x[0] - x[2]) / -4
    x[2] = (10 - x[0] + 2 * x[1]) / -5
    erro_da_iteracao = np.max(np.abs((x - x_anterior) / x) * 100)
    erros.append(erro_da_iteracao)
    if erro_da_iteracao < 0.01:
        break 

In [17]:
x

array([-1.00000096,  2.00000225, -3.00000109])

In [18]:
np.dot(A,x)

array([  2.00000046, -10.00000913,  10.        ])