<a href="https://colab.research.google.com/github/lacouth/metodos_numericos/blob/master/02_sistemas_lineares/SistemasLineares_gauss_pivotacao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Métodos Numéricos

## Resolução de Sistemas Lineares
## O método de Gauss com pivotação

### Patric Lacouth

## O problema

tempo, t | velocidade, v
-----|------
(s)|(m/s)
5|106.8
8|177.2
12|279.2

$$v(t) = at^2 + bt + c$$

## O sistema

$$\left\{\begin{matrix}
25a & + & 5b & + & c & = & 106.8 \\ 
64a & + & 8b & + & c & = & 177.2 \\ 
144a & + & 12b & + & c & = & 279.2 
\end{matrix}\right.$$

## Sistemas Equivalentes

$$\left\{\begin{matrix}
25a & + & 5b & + & c & = & 106.8 \\ 
64a & + & 8b & + & c & = & 177.2 \\ 
144a & + & 12b & + & c & = & 279.2 
\end{matrix}\right.$$

$$\left\{\begin{matrix}
25a & + & 5b & + & c & = & 106.8 \\ 
 &  & 4.80b & - & 1.56c & = & -96.21 \\ 
 &  &  &  & 0.70c & = & 0.76 
\end{matrix}\right.$$

# Operações elementares

1. multiplicação de um linha por uma constante não nula.

2. somar linhas.

3. permutação de duas linhas.

# Implementando Gauss com pivotação em Python

## Importando as bibliotecas

In [ ]:
import numpy as np

## Representando o sistema no python

$$[AB] = \left[ \begin{matrix}
25 & 5 & 1 & 106.8\\
64 & 8 & 1 & 177.2\\
144 & 12 & 1 & 279.2
\end{matrix} \right]$$

In [ ]:
AB = np.array([[25,5,1,106.8],[64,8,1,177.2],[144,12,1,279.2]], dtype = float)
AB

array([[ 25. ,   5. ,   1. , 106.8],
       [ 64. ,   8. ,   1. , 177.2],
       [144. ,  12. ,   1. , 279.2]])

### Selecionando o primeiro pivô

Vamos selecionar o elemento com maior valor absoluto na primeira coluna e trocar as linhas de posição

$$[AB] = \left[ \begin{matrix}
25 & 5 & 1 & 106.8\\
64 & 8 & 1 & 177.2\\
144 & 12 & 1 & 279.2
\end{matrix} \right]$$

In [ ]:
idx = np.argmax(np.abs(AB[:,0]))
idx

2

In [ ]:
AB[[0,idx]] = AB[[idx,0]]
AB

array([[144. ,  12. ,   1. , 279.2],
       [ 64. ,   8. ,   1. , 177.2],
       [ 25. ,   5. ,   1. , 106.8]])

In [ ]:
pivo = AB[0,0]
pivo

144.0

Determinamos o primeiro multiplicador **m1** como sendo o elemento que queremos eliminar dividido pelo nosso pivô

$$[AB] = \left[ \begin{matrix}
25 & 5 & 1 & 106.8\\
64 & 8 & 1 & 177.2\\
144 & 12 & 1 & 279.2
\end{matrix} \right]$$

In [ ]:
m1 = AB[1,0] / pivo
m1

0.4444444444444444

Para zerar o elemento abaixo do pivô iremos subtrair a sua linha pela linha do pivô multiplicada por **m1**

$$[AB] = \left[ \begin{matrix}
25 & 5 & 1 & 106.8\\
64 & 8 & 1 & 177.2\\
144 & 12 & 1 & 279.2
\end{matrix} \right]$$

In [ ]:
AB[1] = AB[1] - AB[0] * m1

In [ ]:
AB

array([[144.        ,  12.        ,   1.        , 279.2       ],
       [  0.        ,   2.66666667,   0.55555556,  53.11111111],
       [ 25.        ,   5.        ,   1.        , 106.8       ]])

Para zerar o próximo elemento da coluna, precisamos de um novo multiplicador, **m2**, que será o próprio elemento dividido pelo pivô

In [ ]:
AB

array([[144.        ,  12.        ,   1.        , 279.2       ],
       [  0.        ,   2.66666667,   0.55555556,  53.11111111],
       [ 25.        ,   5.        ,   1.        , 106.8       ]])

In [ ]:
m2 = AB[2,0] / pivo
m2

0.1736111111111111

Repetimos o processo de subtrair a linha na qual desejamos zerar o elemento pela linha do pivô multiplicada por **m2**

In [ ]:
AB

array([[144.        ,  12.        ,   1.        , 279.2       ],
       [  0.        ,   2.66666667,   0.55555556,  53.11111111],
       [ 25.        ,   5.        ,   1.        , 106.8       ]])

In [ ]:
AB[2] = AB[2] - AB[0]*m2
AB

array([[144.        ,  12.        ,   1.        , 279.2       ],
       [  0.        ,   2.66666667,   0.55555556,  53.11111111],
       [  0.        ,   2.91666667,   0.82638889,  58.32777778]])

## Selecionando o segundo pivô

Vamos selecionar o elemento com maior valor absoluto na segunda coluna, desconsiderando as linhas dos pivôs anteriores, e trocar as linhas de posição

In [ ]:
AB

array([[144.        ,  12.        ,   1.        , 279.2       ],
       [  0.        ,   2.66666667,   0.55555556,  53.11111111],
       [  0.        ,   2.91666667,   0.82638889,  58.32777778]])

In [ ]:
idx = np.argmax(np.abs(AB[1:,1])) + 1
idx

2

In [ ]:
AB[[1,idx]] = AB[[idx,1]]
pivo = AB[1,1]
pivo

2.916666666666667

Nesta coluna temos que realizar apenas a eliminação de um elemento abaixo do pivô, repetimos o mesmo processo anterior, calculamos um multiplicador **m3** a partir da divisão do elemento a ser zerado pelo pivô

In [ ]:
AB

array([[144.        ,  12.        ,   1.        , 279.2       ],
       [  0.        ,   2.91666667,   0.82638889,  58.32777778],
       [  0.        ,   2.66666667,   0.55555556,  53.11111111]])

In [ ]:
m3 = AB[2,1] / pivo

In [ ]:
m3

0.9142857142857143

Com o multiplicador realizamos a operação na linha a ser modificada

In [ ]:
AB[2] = AB[2] - AB[1]*m3

In [ ]:
print(AB)

[[ 1.44000000e+02  1.20000000e+01  1.00000000e+00  2.79200000e+02]
 [ 0.00000000e+00  2.91666667e+00  8.26388889e-01  5.83277778e+01]
 [ 0.00000000e+00  0.00000000e+00 -2.00000000e-01 -2.17142857e-01]]


## Substituição: encontrando os valores de x

Para encontrar $x_3$ precisamos apenas resolver a equação representada pela última linha do sistema

In [ ]:
x = np.zeros(3)
print(AB)

[[ 1.44000000e+02  1.20000000e+01  1.00000000e+00  2.79200000e+02]
 [ 0.00000000e+00  2.91666667e+00  8.26388889e-01  5.83277778e+01]
 [ 0.00000000e+00  0.00000000e+00 -2.00000000e-01 -2.17142857e-01]]


In [ ]:
x[2] = AB[2,3] / AB[2,2]
x

array([0.        , 0.        , 1.08571429])

### Encontrando o valor de $x_2$
Com o valor de $x_3$ definido podemos encontrar $x_2$

In [ ]:
print(AB)

[[ 1.44000000e+02  1.20000000e+01  1.00000000e+00  2.79200000e+02]
 [ 0.00000000e+00  2.91666667e+00  8.26388889e-01  5.83277778e+01]
 [ 0.00000000e+00  0.00000000e+00 -2.00000000e-01 -2.17142857e-01]]


In [ ]:
x[1] = (AB[1,3] - AB[1,2] * x[2]) / AB[1,1]
x

array([ 0.        , 19.69047619,  1.08571429])

Agora com os dois valores de x podemos encontrar $x_1$

In [ ]:
print(AB)

[[ 1.44000000e+02  1.20000000e+01  1.00000000e+00  2.79200000e+02]
 [ 0.00000000e+00  2.91666667e+00  8.26388889e-01  5.83277778e+01]
 [ 0.00000000e+00  0.00000000e+00 -2.00000000e-01 -2.17142857e-01]]


In [ ]:
x[0] = (AB[0,3] - AB[0,2] * x[2] - AB[0,1] * x[1]) / AB[0,0]
x

array([ 0.29047619, 19.69047619,  1.08571429])

## Verificando a resposta

Uma forma de testar se a resposta obtida está correta é fazer o produto de cada linha da matriz de coeficientes com o vetor de icógnitas e verificar se o resultado é igual ao vetor de constantes. 


$$\left[ \begin{matrix}
25 & 5 & 1 \\
64 & 8 & 1\\
144 & 12 & 1
\end{matrix} \right]
\left[ \begin{matrix}
x_{1}\\
x_{2}\\
x_{3}
\end{matrix} \right]
=
\left[ \begin{matrix}
106.8\\
177.2\\
279.2
\end{matrix} \right]
$$

$$[A][x] = [b]$$

In [ ]:
A = np.array([[25,5,1],[64,8,1],[144,12,1]])
x

array([ 0.29047619, 19.69047619,  1.08571429])

In [ ]:
np.dot(A,x)

array([106.8, 177.2, 279.2])

# Now, go code!