# Métodos Numéricos

## Resolução de Sistemas Lineares
## Método de Gauss - Seidel (segundo exemplo)
### Patric Lacouth

Dado o sistema abaixo resolva utilizando o método de Gauss-Seidel com as condições iniciais x = [0,0,0], $\epsilon_a < 0.01$ e no máximo 100 iterações : 

$$\left\{\begin{matrix}
x_1 & + & 10x_2 & + & 3x_3 & = & 27 \\ 
&  & 4x_1 & + & x_3 & = & 6 \\ 
2x_1 & + & x_2 & + & 4x_3 & = & 12 
\end{matrix}\right.$$

# importando as bibliotecas

In [1]:
import numpy as np

## definindo a função que testa a diagonal principal

In [2]:
def diagonal_principal(matriz):
    diag = np.diag(np.abs(matriz))
    soma = np.sum(np.abs(matriz),axis=1) - diag
    r = np.all(diag > soma)
    if r == True:
        print('Matriz com diagonal dominante')
        return True
    else:
        print('Matriz sem diagonal dominante')
        return False

## testando a matriz A
$$\left[ \begin{matrix}
1 & 10 & 3 \\
4 & 0 & 1\\
2 & 1 & 4
\end{matrix} \right]
\left[ \begin{matrix}
x_{1}\\
x_{2}\\
x_{3}
\end{matrix} \right]
=
\left[ \begin{matrix}
27\\
6\\
12
\end{matrix} \right]
$$

In [3]:
A = np.array([[1,10,3],[4,0,1],[2,1,4]],dtype = 'float')
A

array([[ 1., 10.,  3.],
       [ 4.,  0.,  1.],
       [ 2.,  1.,  4.]])

In [4]:
diagonal_principal(A)

Matriz sem diagonal dominante


False

## trocando as linhas
$$\left[ \begin{matrix}
4 & 0 & 1\\
1 & 10 & 3 \\
2 & 1 & 4
\end{matrix} \right]
\left[ \begin{matrix}
x_{1}\\
x_{2}\\
x_{3}
\end{matrix} \right]
=
\left[ \begin{matrix}
6\\
27\\
12
\end{matrix} \right]
$$

In [5]:
A[[0,1]] = A[[1,0]]
A

array([[ 4.,  0.,  1.],
       [ 1., 10.,  3.],
       [ 2.,  1.,  4.]])

In [6]:
diagonal_principal(A)

Matriz com diagonal dominante


True

Dado o sistema abaixo resolva utilizando o método de Gauss-Seidel com as condições iniciais x = [0,0,0], $\epsilon_a < 0.01$ e no máximo 100 iterações : 

$$\left\{\begin{matrix}
&  & 4x_1 & + & x_3 & = & 6 \\
x_1 & + & 10x_2 & + & 3x_3 & = & 27 \\  
2x_1 & + & x_2 & + & 4x_3 & = & 12 
\end{matrix}\right.$$

In [32]:
x = np.array([0,0,0], dtype = 'float')
erros = []
for i in range(100):
    x_anterior = x.copy()
    x[0] = (6 - x[2]) / 4
    x[1] = (27 - x[0] - 3 * x[2]) / 10
    x[2] = (12 - 2 * x[0] - x[2]) / 4
    erro = np.max(np.abs((x - x_anterior) / x) * 100)
    erros.append(erro)
    if erro < 0.0000001:
        break
x

array([1., 2., 2.])

## analisando o erro

In [33]:
erros

[100.0,
 60.0,
 6.976744186046512,
 0.8797653958944283,
 0.10984987184181619,
 0.01373311970702678,
 0.0017166104953565686,
 0.00021457677235049542,
 2.6822089349565224e-05,
 3.3527612811057317e-06,
 4.1909515838180894e-07,
 5.2386894825169985e-08]

In [34]:
len(erros)

12

## verificando a resposta

$$\left[ \begin{matrix}
4 & 0 & 1\\
1 & 10 & 3 \\
2 & 1 & 4
\end{matrix} \right]
\left[ \begin{matrix}
x_{1}\\
x_{2}\\
x_{3}
\end{matrix} \right]
=
\left[ \begin{matrix}
6\\
27\\
12
\end{matrix} \right]
$$

$$[A][x] = [b]$$

In [35]:
np.dot(A,x)

array([ 6., 27., 12.])

# now, go code!