# Métodos Numéricos

## Resolução de Sistemas Lineares
## Método de Gauss - Seidel (segundo exemplo)
### Patric Lacouth

Dado o sistema abaixo resolva utilizando o método de Gauss-Seidel com as condições iniciais x = [0,0,0], $\epsilon_a < 0.01$ e no máximo 100 iterações : 

$$\left\{\begin{matrix}
x_1 & + & 10x_2 & + & 3x_3 & = & 27 \\ 
&  & 4x_1 & + & x_3 & = & 6 \\ 
2x_1 & + & x_2 & + & 4x_3 & = & 12 
\end{matrix}\right.$$

# importando as bibliotecas

In [5]:
import numpy as np

## definindo a função que testa a diagonal principal

In [6]:
def diagonal_dominante(matriz):
    diag = np.diag(np.abs(matriz))
    soma = np.sum(np.abs(matriz),axis=1) - diag
    r = np.all(diag > soma)
    if r == True:
        print('Matriz com diagonal dominante')
        return True
    else:
        print('Matriz sem diagonal dominante')
        return False

## testando a matriz A
$$\left[ \begin{matrix}
1 & 10 & 3 \\
4 & 0 & 1\\
2 & 1 & 4
\end{matrix} \right]
\left[ \begin{matrix}
x_{1}\\
x_{2}\\
x_{3}
\end{matrix} \right]
=
\left[ \begin{matrix}
27\\
6\\
12
\end{matrix} \right]
$$

In [7]:
A = np.array([[1,10,3],[4,0,1],[2,1,4]], dtype = 'float')
A

array([[ 1., 10.,  3.],
       [ 4.,  0.,  1.],
       [ 2.,  1.,  4.]])

In [8]:
diagonal_dominante(A)

Matriz sem diagonal dominante


False

## trocando as linhas
$$\left[ \begin{matrix}
4 & 0 & 1\\
1 & 10 & 3 \\
2 & 1 & 4
\end{matrix} \right]
\left[ \begin{matrix}
x_{1}\\
x_{2}\\
x_{3}
\end{matrix} \right]
=
\left[ \begin{matrix}
6\\
27\\
12
\end{matrix} \right]
$$

In [9]:
A[[0,1]] = A[[1,0]]
A

array([[ 4.,  0.,  1.],
       [ 1., 10.,  3.],
       [ 2.,  1.,  4.]])

In [10]:
diagonal_dominante(A)

Matriz com diagonal dominante


True

Com o sistema reescrito encontre a solução utilizando o método de Gauss-Seidel com as condições iniciais x = [0,0,0], $\epsilon_a < 0.01$ e no máximo 100 iterações : 

$$\left\{\begin{matrix}
&  & 4x_1 & + & x_3 & = & 6 \\
x_1 & + & 10x_2 & + & 3x_3 & = & 27 \\  
2x_1 & + & x_2 & + & 4x_3 & = & 12 
\end{matrix}\right.$$

In [15]:
x = np.array([0,0,0], dtype = 'float')
erros = []
for i in range(100):
    x_anterior = x.copy()
    x[0] = (6 - x[2]) / 4
    x[1] = (27 - x[0] - 3 * x[2]) / 10
    x[2] = (12 - 2 * x[0] - x[1]) / 4
    erro = np.max(np.abs((x - x_anterior) / x) * 100)
    erros.append(erro)
    if erro < 0.00001:
        break

x

array([1.00000001, 2.00000001, 1.99999999])

## analisando o erro

In [16]:
erros

[100.0,
 36.75213675213675,
 7.666647495255077,
 1.5078101596111981,
 0.2929941663623924,
 0.05679986366331927,
 0.011006184812482897,
 0.0021324937817447285,
 0.00041317237734621196,
 8.005221218018869e-05,
 1.551011852207151e-05,
 3.0050855586751917e-06]

In [17]:
len(erros)

12

## verificando a resposta

$$\left[ \begin{matrix}
4 & 0 & 1\\
1 & 10 & 3 \\
2 & 1 & 4
\end{matrix} \right]
\left[ \begin{matrix}
x_{1}\\
x_{2}\\
x_{3}
\end{matrix} \right]
=
\left[ \begin{matrix}
6\\
27\\
12
\end{matrix} \right]
$$

$$[A][x] = [b]$$

In [18]:
np.dot(A,x)

array([ 6.00000002, 27.00000007, 12.        ])

# now, go code!