# Métodos Numéricos

## Resolução de Sistemas Lineares
## Método de Gauss - Seidel (teste da diagonal dominante)

### Patric Lacouth

# importando as bibliotecas

In [1]:
import numpy as np

Dado o sistema abaixo resolva utilizando o método de Gauss-Seidel com as condições iniciais x = [0,0,0], $\epsilon_a < 0.001$ e no máximo 100 iterações : 

$$\left\{\begin{matrix}
25x_1 & + & 5x_2 & + & x_3 & = & 106.8 \\ 
64x_1 & + & 8x_2 & + & x_3 & = & 177.2 \\ 
144x_1 & + & 12x_2 & + & x_3 & = & 279.2 
\end{matrix}\right.$$

In [2]:
x = np.array([0,0,0], dtype = 'float')
erros = []
for i in range(100):
    x_anterior = x.copy()
    x[0] = (106.8 - 5 * x[1] - x[2] ) / 25
    x[1] = (177.2 - 64 * x[0] - x[2]) / 8
    x[2] = (279.2 - 144 * x[0] - 12*x[1]) / 1
    erro = np.max(np.abs((x - x_anterior) / x) * 100)
    erros.append(erro)
    if erro < 0.001:
        break

In [3]:
x

array([ 5.35230124e+61, -3.07145993e+62, -4.02156187e+63])

## Analisando o erro

In [4]:
print(erros)

[100.0, 82.47973645887298, 77.82583797158112, 76.46198280081241, 76.07037114997655, 75.96175895858617, 75.93252471109473, 75.92483510936093, 75.92284730722305, 75.92234020216463, 75.92221215476253, 75.92218008228413, 75.92217210081952, 75.92217012497778, 75.92216963795141, 75.92216951833043, 75.92216948903669, 75.92216948188077, 75.92216948013638, 75.92216947971188, 75.92216947960875, 75.92216947958372, 75.92216947957765, 75.9221694795762, 75.92216947957584, 75.92216947957576, 75.92216947957574, 75.92216947957571, 75.92216947957571, 75.92216947957571, 75.9221694795757, 75.92216947957571, 75.9221694795757, 75.92216947957571, 75.92216947957573, 75.92216947957571, 75.92216947957571, 75.92216947957571, 75.92216947957571, 75.92216947957571, 75.92216947957571, 75.92216947957571, 75.92216947957571, 75.92216947957571, 75.92216947957571, 75.92216947957571, 75.92216947957571, 75.92216947957571, 75.92216947957571, 75.92216947957573, 75.92216947957571, 75.92216947957571, 75.92216947957571, 75.9221

In [5]:
len(erros)

100

## Verificando a dominância da diagonal
$$\left[ \begin{matrix}
25 & 5 & 1 \\
64 & 8 & 1\\
144 & 12 & 1
\end{matrix} \right]
\left[ \begin{matrix}
x_{1}\\
x_{2}\\
x_{3}
\end{matrix} \right]
=
\left[ \begin{matrix}
106.8\\
177.2\\
279.2
\end{matrix} \right]
$$

In [7]:
A = np.array([[25,5,1],[64,8,1],[144,12,1]], dtype = 'float')
A

array([[ 25.,   5.,   1.],
       [ 64.,   8.,   1.],
       [144.,  12.,   1.]])

### Extraindo a diagonal

In [11]:
diag = np.diag(np.abs(A))
diag

array([25.,  8.,  1.])

### Somando as linhas e subtraindo o elemento da diagonal

In [12]:
A

array([[ 25.,   5.,   1.],
       [ 64.,   8.,   1.],
       [144.,  12.,   1.]])

In [17]:
soma = np.sum(np.abs(A),axis = 1) - diag
soma

array([  6.,  65., 156.])

### Comparando os elementos da diagonal com a soma

In [18]:
A

array([[ 25.,   5.,   1.],
       [ 64.,   8.,   1.],
       [144.,  12.,   1.]])

In [20]:
np.all(diag > soma)

False

### Juntando tudo em uma função

In [21]:
def diagonal_dominante(matriz):
    diag = np.diag(np.abs(matriz))
    soma = np.sum(np.abs(matriz),axis = 1) - diag
    resultado = diag > soma
    if np.all(resultado) == True:
        print("A matriz possui diagonal dominante")
        return True
    else:
        print("A matriz não possui diagonal dominante")
        return False

### Testando a função

$$\left[ \begin{matrix}
25 & 5 & 1 \\
64 & 8 & 1\\
144 & 12 & 1
\end{matrix} \right]$$

In [22]:
diagonal_dominante(A)

A matriz não possui diagonal dominante


False

### Testando a função

$$\left[ \begin{matrix}
5 & 1 & 1 \\
-1 & 3 & 1\\
1 & 2 & 10
\end{matrix} \right]$$

In [23]:
M = np.array([[5,1,1],[-1,3,1],[1,2,10]], dtype = 'float')
diagonal_dominante(M)

A matriz possui diagonal dominante


True

# Now, go code!