# Métodos Numéricos

## Resolução de Sistemas Lineares
## O método de Gauss Ingênuo

### Patric Lacouth

## O problema

tempo, t | velocidade, v
-----|------
(s)|(m/s)
5|106.8
8|177.2
12|279.2

$$v(t) = at^2 + bt + c$$

## O sistema

$$\left\{\begin{matrix}
25a & + & 5b & + & c & = & 106.8 \\ 
64a & + & 8b & + & c & = & 177.2 \\ 
144a & + & 12b & + & c & = & 279.2 
\end{matrix}\right.$$

## Sistemas Equivalentes

$$\left\{\begin{matrix}
25a & + & 5b & + & c & = & 106.8 \\ 
64a & + & 8b & + & c & = & 177.2 \\ 
144a & + & 12b & + & c & = & 279.2 
\end{matrix}\right.$$

$$\left\{\begin{matrix}
25a & + & 5b & + & c & = & 106.8 \\ 
 &  & 4.80b & - & 1.56c & = & -96.21 \\ 
 &  &  &  & 0.70c & = & 0.76 
\end{matrix}\right.$$

# Método de Gauss Ingênuo

* Método **direto**

* Método matricial

# As etapas

* Eliminação progressiva

 * Substituição retroativa

<img src = "imagens/exemplo_eliminacao.png" width = 50% style = "display : block; margin-right : auto; margin-left : auto;" />

# Operações elementares

1. multiplicação de um linha por uma constante não nula.

2. somar linhas.

3. permutação de duas linhas.

# Representação Matricial

$$\left\{\begin{matrix}
25x_1 & + & 5x_2 & + & x_3 & = & 106.8 \\ 
64x_1 & + & 8x_2 & + & x_3 & = & 177.2 \\ 
144x_1 & + & 12x_2 & + & x_3 & = & 279.2 
\end{matrix}\right.$$

$$\left[ \begin{matrix}
25 & 5 & 1 \\
64 & 8 & 1\\
144 & 12 & 1
\end{matrix} \right]
\left[ \begin{matrix}
x_{1}\\
x_{2}\\
x_{3}
\end{matrix} \right]
=
\left[ \begin{matrix}
106.8\\
177.2\\
279.2
\end{matrix} \right]
$$

$$[A][x] = [b]$$

# Matriz Estendida

como vamos fazer operações com as matrizes $[A]$ e $[b]$ no python podemos representar as duas matrizes através de uma matriz estendida que contém todos os valores



$$\left[ \begin{matrix}
25 & 5 & 1 \\
64 & 8 & 1\\
144 & 12 & 1
\end{matrix} \right]
\left[ \begin{matrix}
x_{1}\\
x_{2}\\
x_{3}
\end{matrix} \right]
=
\left[ \begin{matrix}
106.8\\
177.2\\
279.2
\end{matrix} \right]
$$

$$[AB] = \left[ \begin{matrix}
25 & 5 & 1 & 106.8\\
64 & 8 & 1 & 177.2\\
144 & 12 & 1 & 279.2
\end{matrix} \right]$$

# O algoritmo da eliminação progressiva

1. Determinar o **pivô**

$$[AB] = \left[ \begin{matrix}
25 & 5 & 1 & 106.8\\
64 & 8 & 1 & 177.2\\
144 & 12 & 1 & 279.2
\end{matrix} \right]$$

2. Criar o multiplicador, **$m_x$** , para escalonar a linha

3. Subtrair a linha do elemento a ser zerado pela linha do pivô escalonada pelo multiplicador.

4. Repetir o processo para todos os valores a serem eliminados

# Implementando Gauss Ingênuo em Python

## Importando as bibliotecas

In [12]:
import numpy as np

## Representando o sistema no python

$$[AB] = \left[ \begin{matrix}
25 & 5 & 1 & 106.8\\
64 & 8 & 1 & 177.2\\
144 & 12 & 1 & 279.2
\end{matrix} \right]$$

In [13]:
AB = np.array([[25,5,1,106.8],[64,8,1,177.2],[144,12,1,279.2]], dtype = float)
AB

array([[ 25. ,   5. ,   1. , 106.8],
       [ 64. ,   8. ,   1. , 177.2],
       [144. ,  12. ,   1. , 279.2]])

### Selecionando o primeiro pivô

Precisamos "zerar" os elementos abaixo do primeiro elemento da primeira coluna, para isso escolhemos o elemento $a_{11}$ como sendo o pivô que irá gerar o multiplicadores

$$[AB] = \left[ \begin{matrix}
25 & 5 & 1 & 106.8\\
64 & 8 & 1 & 177.2\\
144 & 12 & 1 & 279.2
\end{matrix} \right]$$

In [14]:
pivo = AB[0,0]
pivo

25.0

Determinamos o primeiro multiplicador **m1** como sendo o elemento que queremos eliminar dividido pelo nosso pivô

$$[AB] = \left[ \begin{matrix}
25 & 5 & 1 & 106.8\\
64 & 8 & 1 & 177.2\\
144 & 12 & 1 & 279.2
\end{matrix} \right]$$

In [15]:
m1 = AB[1,0] / pivo
m1

2.56

Para zerar o elemento abaixo do pivô iremos subtrair a sua linha pela linha do pivô multiplicada por **m1**

$$[AB] = \left[ \begin{matrix}
25 & 5 & 1 & 106.8\\
64 & 8 & 1 & 177.2\\
144 & 12 & 1 & 279.2
\end{matrix} \right]$$

In [16]:
AB[1,:] = AB[1,:] - AB[0,:]*m1

In [17]:
AB

array([[ 25.   ,   5.   ,   1.   , 106.8  ],
       [  0.   ,  -4.8  ,  -1.56 , -96.208],
       [144.   ,  12.   ,   1.   , 279.2  ]])

Para zerar o próximo elemento da coluna, precisamos de um novo multiplicador, **m2**, que será o próprio elemento dividido pelo pivô

In [18]:
AB

array([[ 25.   ,   5.   ,   1.   , 106.8  ],
       [  0.   ,  -4.8  ,  -1.56 , -96.208],
       [144.   ,  12.   ,   1.   , 279.2  ]])

In [19]:
m2 = AB[2,0] / pivo
m2

5.76

Repetimos o processo de subtrair a linha na qual desejamos zerar o elemento pela linha do pivô multiplicada por **m2**

In [20]:
AB[2,:] = AB[2,:] - AB[0,:] * m2

In [21]:
AB

array([[  25.   ,    5.   ,    1.   ,  106.8  ],
       [   0.   ,   -4.8  ,   -1.56 ,  -96.208],
       [   0.   ,  -16.8  ,   -4.76 , -335.968]])

## Selecionando o segundo pivô

Depois de "eliminar" os elementos da primeira coluna temos que continuar a eliminação na segunda coluna. O pivô agora passa a ser o elemento $a_{22}$ 

In [22]:
AB

array([[  25.   ,    5.   ,    1.   ,  106.8  ],
       [   0.   ,   -4.8  ,   -1.56 ,  -96.208],
       [   0.   ,  -16.8  ,   -4.76 , -335.968]])

In [23]:
pivo = AB[1,1]
pivo

-4.800000000000001

Nesta coluna temos que realizar apenas a eliminação de um elemento abaixo do pivô, repetimos o mesmo processo anterior, calculamos um multiplicador **m3** a partir da divisão do elemento a ser zerado pelo pivô

In [24]:
AB

array([[  25.   ,    5.   ,    1.   ,  106.8  ],
       [   0.   ,   -4.8  ,   -1.56 ,  -96.208],
       [   0.   ,  -16.8  ,   -4.76 , -335.968]])

In [25]:
m3 = AB[2,1] / pivo

In [26]:
m3

3.499999999999999

Com o multiplicador realizamos a operação na linha a ser modificada

In [27]:
AB[2,:] = AB[2,:] - AB[1,:] * m3

In [28]:
AB

array([[ 25.   ,   5.   ,   1.   , 106.8  ],
       [  0.   ,  -4.8  ,  -1.56 , -96.208],
       [  0.   ,   0.   ,   0.7  ,   0.76 ]])

## Substituição: encontrando os valores de x

Para encontrar $x_3$ precisamos apenas resolver a equação representada pela última linha do sistema

In [30]:
x = np.zeros(3)
AB

array([[ 25.   ,   5.   ,   1.   , 106.8  ],
       [  0.   ,  -4.8  ,  -1.56 , -96.208],
       [  0.   ,   0.   ,   0.7  ,   0.76 ]])

In [31]:
x[2] = AB[2,3] / AB[2,2]
x

array([0.        , 0.        , 1.08571429])

### Encontrando o valor de $x_2$
Com o valor de $x_3$ definido podemos encontrar $x_2$

In [32]:
AB

array([[ 25.   ,   5.   ,   1.   , 106.8  ],
       [  0.   ,  -4.8  ,  -1.56 , -96.208],
       [  0.   ,   0.   ,   0.7  ,   0.76 ]])

In [33]:
x[1] = (AB[1,3] - AB[1,2] * x[2]) / AB[1,1]
x

array([ 0.        , 19.69047619,  1.08571429])

Agora com os dois valores de x podemos encontrar $x_1$

In [34]:
AB

array([[ 25.   ,   5.   ,   1.   , 106.8  ],
       [  0.   ,  -4.8  ,  -1.56 , -96.208],
       [  0.   ,   0.   ,   0.7  ,   0.76 ]])

In [35]:
x[0] = (AB[0,3] - AB[0,2] * x[2] - AB[0,1] * x[1]) / AB[0,0]
x

array([ 0.29047619, 19.69047619,  1.08571429])

## Verificando a resposta

Uma forma de testar se a resposta obtida está correta é fazer o produto de cada linha da matriz de coeficientes com o vetor de icógnitas e verificar se o resultado é igual ao vetor de constantes. 

**Primeira linha**

$$\left[ \begin{matrix}
25 & 5 & 1 \\
64 & 8 & 1\\
144 & 12 & 1
\end{matrix} \right]
\left[ \begin{matrix}
x_{1}\\
x_{2}\\
x_{3}
\end{matrix} \right]
=
\left[ \begin{matrix}
106.8\\
177.2\\
279.2
\end{matrix} \right]
$$

$$[A][x] = [b]$$

In [36]:
A = np.array([[25,5,1],[64,8,1],[144,12,1]])
A

array([[ 25,   5,   1],
       [ 64,   8,   1],
       [144,  12,   1]])

In [40]:
B = np.dot(A,x)
B

array([106.8, 177.2, 279.2])

# Por que ingênuo?

$$[AB] = \left[ \begin{matrix}
0 & 5 & 1 & 106.8\\
64 & 8 & 1 & 177.2\\
144 & 12 & 1 & 279.2
\end{matrix} \right]$$

# Now, go code!